### ISSUE TITLE
Change Organization Model to Group Table, Modals for Certificates and Groups

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#100]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
As of now, there is an organization table and various extra fields are there in tables. Also, separate pages are being used to certificate addition and editing as well as group addition and editing.

### Describe the solution you'd like
The organization table needs to be changed to group table and instead of extra pages, we can use modals which also makes it easy for users to manage the groups and certificates.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Assigning to you @ashutoshkrris
