### ISSUE TITLE
Gssoc'21 New And Cool Toggle Button

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#122]
### Is your feature request related to a problem? Please describe.
I want to replace the normal toggle button to a new and cool toggle button 
### Describe the solution you'd like
currently toggle button is looking this .
<img width="960" alt="flask2" src="https://user-images.githubusercontent.com/55352601/112594125-6fc8c300-8e2e-11eb-90ad-40512d572f7a.png">

### Describe alternatives you've considered
I will make a new and cool toggle  for that.
### Which Program are you part of?

- [x] GSSOC21
- [] Any other

### Additional context

Kindly assign me this issue.

**Comment by arpit456jain** [comment]
@vigneshshettyin sir kindly assign me this issue. The work is done I just Have to open a PR. I will be attach the sample video in it.

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin sir kindly assign me this issue. The work is done I just Have to open a PR. I will be attach the sample video in it.

@arpit456jain assigning to you.
