### ISSUE TITLE
Bug in Register page

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#140]
### **Describe the bug**
There is bug or I should say (something irritating) in register page in password fields.
When I enter password it flashes the error which is ok.
but because of this error the whole page got affected for sec which is very irritating, at-least for me
I want solve this issue

I am attaching a  video for better understanding of my issue.

https://user-images.githubusercontent.com/55352601/112672455-82bcb100-8e89-11eb-8c19-063c4ab7fbb5.mp4

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by arpit456jain** [comment]
@vigneshshettyin sir Kindly assign me this issue.
I will try to improve the current Design of  login/register page as much as possible for now.
In future I will surely make a new and better login/signup page for this project.

**Comment by shades-7** [comment]
@arpit456jain Thanks for pointing out these issues. :pray:  you have added 3 issues, it will be great if you will open 3 different issues and edit this issue as one of them. we will be pleased to assign you this.

**Comment by arpit456jain** [comment]
Ok @shades-7 mam i will solve only bug in register page and will create new issues for others kindly assign this to me..

**Comment by shades-7** [comment]
First edit the above issue and write the one issue that you will be fixing in this, so it will be clear for all of us

**Comment by arpit456jain** [comment]
ok @shades-7

**Comment by arpit456jain** [comment]
I had updated the comment. kindly assign it to me . @shades-7

**Comment by shades-7** [comment]
Thank you @arpit456jain assigned to you go ahead

**Comment by arpit456jain** [comment]
thank you @shades-7

**Comment by arpit456jain** [comment]
@vigneshshettyin sir the the issue is already open kindly re assign me this issue .

**Comment by vigneshshettyin** [comment]
Yup, @arpit456jain I have already assigned it to you.

**Comment by arpit456jain** [comment]
Yes sir thank you i will create a PR as soon as possible

**Comment by vigneshshettyin** [comment]
Cool @arpit456jain

**Comment by arpit456jain** [comment]
@vigneshshettyin sir  the work is done may I create a PR ?

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin sir  the work is done may I create a PR ?

Yup, proceed
