### ISSUE TITLE
Email Verification 

### ISSUE THREAD

**Issue by Tom-Stack-UX** [vigneshshettyin/Flask-Generate-Certificate#15]
### Is your feature request related to a problem?
Checking whether email address is genuine by generating a email to that email address which has a verification link such that it expires after some hours or seconds.

### Describe the solution you'd like
For reference : https://youtu.be/vF9n248M1yk

### Describe alternatives you've considered
Haven't found any alternatives.

### Describe how this feature will be useful to our readers.
This would not allow fake users to login in. Lot of stress on the server can be reduced.

### Additional context
No

<hr/>

Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.  
If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.  
Then you can directly start working on the issue.

**Comment by ashutoshkrris** [comment]
Also, we can opt for OTP verification during signup which allows only genuine users to register.
I can work on it if it's assigned to me.

**Comment by vigneshshettyin** [comment]
Yup, you can work on it.

**Comment by APratham** [comment]
@ashutoshkrris @Tom-Stack-UX Please let me know if more days are required for implementing the solution. As a mentor, I have to remind within 2-3 days of an issue being opened. Please note that if there is no more progress after another 3 days, this issue can be closed for GSSOC contribution

**Comment by ashutoshkrris** [comment]
@APratham yes, i am working on this issue.
I am constantly in touch with @vigneshshettyin about the changes that needs to be done.
