### ISSUE TITLE
Design changes in flash message

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Flask-Generate-Certificate#150]
### Is your feature request related to a problem? Please describe.
The current flash message looks bad. Instead of it, we can have a small flash message at the top corner right with a button to close that as well or any new library will do. 

### Describe the solution you'd like
Check for it in bootstrap docs (https://getbootstrap.com/docs/4.0/components/alerts/) 

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

### Additional context
![Flash Message](https://user-images.githubusercontent.com/77713888/112744184-6325a580-8fbb-11eb-8240-93ff35ab2e30.png)

**Comment by ashutoshkrris** [comment]
Talking about bootstrap alerts, it will be almost same as flask flash.
We can use simple-notify to do so. It is customizable also. We can add custom class, icons, speed, effects, text, etc. The only thing is we need to use ajax requests to send the notifications.

**Comment by vigneshshettyin** [comment]
> Talking about bootstrap alerts, it will be almost same as flask flash.
> We can use simple-notify to do so. It is customizable also. We can add custom class, icons, speed, effects, text, etc. The only thing is we need to use ajax requests to send the notifications.

Yup, that's great @ashutoshkrris. Can you work on it ?

**Comment by arpit456jain** [comment]
@vigneshshettyin sir  please assign it to me .
Let me try that.

**Comment by arpit456jain** [comment]
I think We just have to replace it with bootstrap version 4 alert.

**Comment by ashutoshkrris** [comment]
> I think We just have to replace it with bootstrap version 4 alert.

But changing it won't change much..
Bootstrap alerts are almost same as flask messages

**Comment by arpit456jain** [comment]
> > I think We just have to replace it with bootstrap version 4 alert.
> 
> But changing it won't change much..
> Bootstrap alerts are almost same as flask messages

I agree .

In issue sir asked "The current flask message looks bad. Instead of it, we can have a small flask message at the top corner right with a button to close that as well.
"
The alert is ok only the button was not showing to close that alert that's why I suggest to update the classes to version 4

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain let's avoid using bootstrap alerts. Let's try something new like what @ashutoshkrris suggested. Check for some good library's for alerts.

**Comment by arpit456jain** [comment]
> Hey, @arpit456jain let's avoid using bootstrap alerts. Let's try something new like what @ashutoshkrris suggested. Check for some good library's for alerts.

Ok sir
