### ISSUE TITLE
[Gssoc'21] Size of dark mode toggle is too big

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#158]
### **Describe the bug**
Size of dark mode toggle is too big
### **Expected behavior**
Its size should be decrease little bit in Desktop view and little bit more for phone view

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by arpit456jain** [comment]
@vigneshshettyin sir kindly assign me this issue so i can create a PR.

**Comment by vigneshshettyin** [comment]
Sure assigning to you. @arpit456jain

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly review my fresh PR  #169
