### ISSUE TITLE
Certificate PDF Conversion without API

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#160]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
Currently, for converting certificate from HTML to PDF, we're calling an API service, which has a limit. 

### Describe the solution you'd like
Instead of calling API, we can use wkhtmltopdf and pdfkit to generate PDF on our own and user can download it by clicking on the download button

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Okay, @ashutoshkrris Assigning to you.
