### ISSUE TITLE
[Gssoc'21] Add a show password button

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#163]
I want to Add a show password **[checkbox]** button
because when I am creating a password there is chance I got forget what I type in password field
then it is very difficult for anyone to enter same password in both or may be any wrong key got pressed.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly assign it to me.
I want to add this in both login/signup page

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin kindly assign it to me.
> I want to add this in both login/signup page

Okay @arpit456jain assigning to you.

**Comment by arpit456jain** [comment]
@vigneshshettyin please merge PR #159 so I can start working on new issues
If any changes needed to be done in toggle I will do it no problem

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin please merge PR #159 so I can start working on new issues
> If any changes needed to be done in toggle I will do it no problem 

Hey, @arpit456jain all design changes will be approved by @shades-7. She will look into it soon. Till then you can work on the new issue assigned.
