### ISSUE TITLE
Tokens getting re-used

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#165]
### **Describe the bug**
The verification links or the activation links being sent that I had implemented could be used more than once.

### **To Reproduce**
1. Go to register page and sign up for an account
2. Activate your account using the link.
3. Click on the link again after using the link.

### **Expected behavior**
Once the token is used, it should expire so that it cannot be used again.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Assigned to you. @ashutoshkrris
