### ISSUE TITLE
Issues in style.css

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#171]
### **Describe the bug**
There are some issues in style.css

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

### **Screenshots**
<img width="960" alt="Untitled2" src="https://user-images.githubusercontent.com/55352601/113097511-a2026800-9214-11eb-893b-d26e1c6f8e03.png">
<img width="960" alt="Untitled3" src="https://user-images.githubusercontent.com/55352601/113097516-a4fd5880-9214-11eb-8ff6-a702c94b4f30.png">

### **Additional context**
I would like to resolve these issues as much as possible.

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly assign me this issue.

**Comment by vigneshshettyin** [comment]
Yes @arpit456jain assigning to you.

**Comment by arpit456jain** [comment]
@vigneshshettyin sir when i run pip install requirements.txt this time 1 error occur see this.
<img width="960" alt="Untitled7" src="https://user-images.githubusercontent.com/55352601/113099501-ad0ac780-9217-11eb-8509-266f680cc4d0.png">
kindly check this.
although the website is running fine no problem. I just informed you about this.

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin sir when i run pip install requirements.txt this time 1 error occur see this.
> <img width="960" alt="Untitled7" src="https://user-images.githubusercontent.com/55352601/113099501-ad0ac780-9217-11eb-8509-266f680cc4d0.png">
> kindly check this.
> although the website is running fine no problem. I just informed you about this.

Hey, @arpit456jain  thanks for letting us know. We will look into it.
