### ISSUE TITLE
Auto Label Bot 

### ISSUE THREAD

**Issue by aishux** [vigneshshettyin/Flask-Generate-Certificate#174]
### Is your feature request related to a problem? Please describe.
Add GitHub action to auto label issues with gssoc21 label when contributor asks to work under gssoc21. As it takes time for the maintainer to add labels, I can add a script that can auto-label issues with the GSSOC21 label whenever contributors ask to work under that label.

Describe the solution you'd like
I would like to add a script to automate the process.

### Describe alternatives you've considered
None

### Describe how this feature will be useful to our readers.
It will reduce the work load of the maintainer

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

### Additional context
Please assign me this issue with a GSSOC tag

**Comment by vigneshshettyin** [comment]
Yup, @aishux assigning to you.

**Comment by aishux** [comment]
Can you please assign me a level tag too?

**Comment by vigneshshettyin** [comment]
> Can you please assign me a level tag too?

Assigned @aishux
