### ISSUE TITLE
[Gssoc'21] Bug in Login feature on main page

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#177]
### **Describe the bug**
There is a login button on main page by which user can login and that's ok.
but when a user is successfully logged in It should show **Log Out** but it still says login and if i click on login then it redirect me to dashboard.
Check this video.

https://user-images.githubusercontent.com/55352601/113258275-5ff72600-92e9-11eb-81d4-4c0e5677589d.mp4

 
### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly assign me this issue

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain. I'll assign this issue to you. Try to add logged in users avatar and name there. 

All the best!

**Comment by arpit456jain** [comment]
Ok i will give my best

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly review my PR
