### ISSUE TITLE
bug in main page in login in dark mode

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#179]
### **Describe the bug**
There is some bug in login/logout in dark-mode which is my fault I should check it before creating a  PR 
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/55352601/113266554-085db800-92f3-11eb-8ce3-a4abfa49e08c.png">

### **Expected behavior**
It should look like this
<img width="960" alt="Untitled2" src="https://user-images.githubusercontent.com/55352601/113266687-2deac180-92f3-11eb-86f1-da9056d551d8.png">

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by arpit456jain** [comment]
@vigneshshettyin I am sorry there are some bugs in my previous PR in dark mode .
I had solved them

**Comment by arpit456jain** [comment]
Kindly assign me  the issue so I can create a PR for that.

**Comment by vigneshshettyin** [comment]
> Kindly assign me  the issue so I can create a PR for that.

Yup, @arpit456jain assigning to you.
