### ISSUE TITLE
Live deployment in the readme to open in a new tab 

### ISSUE THREAD

**Issue by akshay1027** [vigneshshettyin/Flask-Generate-Certificate#185]
### What part(s) of the article would you like to see updated?
Live deployment in the readme to open in a new tab so that it is easier for the user to navigate to GitHub codebase.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Assigning to you @akshay1027

**Comment by vigneshshettyin** [comment]
Any update @akshay1027?

**Comment by akshay1027** [comment]
Hey @vigneshshettyin I found out later that it's not possible to do this on GitHub, we cant do target="_blank" or any such thing in GitHub in .md format, so I am closing this issue! Sorry
check this out!
https://stackoverflow.com/questions/3492153/markdown-open-a-new-window-link
