### ISSUE TITLE
Show only logged in user's details

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#186]
### **Describe the bug**
As of now, a user can view the details(groups, certificates, etc.) of other users also.

### **To Reproduce**
1. Go to dashboard
2. Click on groups
3. Go to certificates

### **Expected behavior**
Ideally, a user should be able to see groups and certificates which are assigned to it only.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Okay, assigned @ashutoshkrris
