### ISSUE TITLE
Admin or Staff Required Middleware

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#188]
### **Describe the bug**
As of now, every user is able to view the contacts, users, feedback, newsletters tables 

### **To Reproduce**
1. Go to 'dashboard'
2. Click on 'any of the above mentioned menu'
3. See error

### **Expected behavior**
Ideally, only admin should be able to view those tables and if a common user tries to access the page, using menu button or via direct url, should be shown appropriate error.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Assigned @ashutoshkrris
