### ISSUE TITLE
Show Transaction Table for Admin

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#190]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
As of now, transaction is recorded but the admin cannot see it. To see it, admin have to directly view using the database file. 

### Describe the solution you'd like
The transaction table can be added in the menu for the admin to view the transactions.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Assigned @ashutoshkrris
