### ISSUE TITLE
Replace import.json with .env file

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#192]
### **Describe the bug**
For now, we have kept all the secrets in a import.json file which is not a standard way to store those data.

### **Expected behavior**
The standard way to store those data is to use a .env file which will be helpful during deployment as well.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Assigned @ashutoshkrris
