### ISSUE TITLE
Separated Email Function and templates

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#194]
### **Describe the bug**
Everything is working fine, but for sending email, we are writing separate code each time which violates the DRY(Don't Repeat Yourself) principle.

### **Expected behavior**
Instead of writing the same code everytime for sending email, we can write a function and call it each time we need to send email.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Assigned @ashutoshkrris
