### ISSUE TITLE
Add hover effect to social icons.

### ISSUE THREAD

**Issue by Aayush-hub** [vigneshshettyin/Flask-Generate-Certificate#2]
Hover effects of different colours can be added to social icons so that they look awesome.

**Comment by Aayush-hub** [comment]
@vigneshshettyin Can you assign me this for GSSoC21?

**Comment by vigneshshettyin** [comment]
Yup, Go ahead!

**Comment by Aayush-hub** [comment]
@vigneshshettyin I can make a PR now or have to wait till 8th March?

**Comment by vigneshshettyin** [comment]
You make a PR. I'll have a word from the organizers by then. As your PR must be labeled.

**Comment by Aayush-hub** [comment]
@vigneshshettyin Sir, please review my PR as GssoC21 participant and suggest me changes if any. As it looks a silly change, but it took me 1.5 hour to realize what's the exact problem. The program is very much overwritten and it does not reflect changes by changing many files.

**Comment by vigneshshettyin** [comment]
Hey @Aayush-hub I just had a word with the organizer. They were like contributions done after 8th March will be counted. So as of know I'll keep your pull request on hold. Will accept once the event starts. 

Thanks for contributing!

**Comment by Aayush-hub** [comment]
@vigneshshettyin Sure, Thanx for your support! Looking forward for further contributions:)
