### ISSUE TITLE
Bug in quick start guide

### ISSUE THREAD

**Issue by Aayush-hub** [vigneshshettyin/Flask-Generate-Certificate#20]
### **Describe the bug**
pip3 install requirements.txt doesn't work.
GSSOC

![1](https://user-images.githubusercontent.com/65889104/110665964-e343c100-81ee-11eb-804c-d6d528f76ab5.png)

**Comment by APratham** [comment]
@Aayush-hub Although I appreciate you making a contribution, this is not acceptable, You have to wait for a mentor or the project maintainer to assign the issue to you _before_ starting to work on it. You have done neither of them, so now tell me how is either the issue or the PR valid? I can't add labels after you have created the PR right? Neither can I assign it to you now.

**Comment by Aayush-hub** [comment]
@APratham Sir, you are absolutely correct, but in my opinion what's the use of auto-assigning workflow in the project if a contributor can't assign himself the issue. And I think it is also essential for the way GSSOC is going on, because if a contributor has raised any issue then he or she should get atleast 7 days to make a PR for a assigned issue, but under GSSOC spamming is going on in common, and I have faced it in many projects. Though I apologize for my act, will take care of it next time. Looking forward for further contributions :)
