### ISSUE TITLE
Replace Feedback modal with SweetAlert2 Modal

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#200]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
The Bootstrap modal used for feedback looks old-fashioned.

### Describe the solution you'd like
Instead of bootstrap modal, we can use SweetAlert2

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Assigned to you. @ashutoshkrris
