### ISSUE TITLE
Remove extra model fields

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#202]
### **Describe the bug**
Earlier there were few model fields that are not there now, but they are still used at few places.

### **To Reproduce**
1. Go to Login
2. Click on Login with Google
3. See error

### **Expected behavior**
Those extra fields should be removed or replaced with the updated fields.
Also facebook auth is not working properly

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by shades-7** [comment]
@ashutoshkrris would you like to work on this?

**Comment by ashutoshkrris** [comment]
yes @shades-7
