### ISSUE TITLE
Bugs after deployment

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#206]
### **Describe the bug**
A lot of bugs have been found after the app is deployed. 
Some of them are : 
1. Double Notifications
2.  Users Activation/Deactivation Not Working
3.  Newsletter Bug
4. Contact Form Bug

### **Expected behavior**
I'll fix all the above mentioned bugs in one PR with separate commits for each bug.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Assigned @ashutoshkrris
