### ISSUE TITLE
Google Login for deactivated users [bug]

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#210]
### **Describe the bug**
Once a user logs in with google, his/her account is activated. But there may be conditions when the admin deactivates his/her account. But the user was still able to login.

### **Expected behavior**
In the above mentioned condition, the user must not be able to login.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Assigned @ashutoshkrris
