### ISSUE TITLE
[Gssoc'21] Preloader

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#212]
I would like to add a pre-loader to website as some time it takes a log time to load all the file
### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain assigned to you.

**Comment by arpit456jain** [comment]
Thanks @vigneshshettyin i just start working right now

**Comment by arpit456jain** [comment]
@vigneshshettyin some work I had already done in this evening after when i raised this issue like js part
I had made 2 pre loaders kindly select 1 what you like.

https://user-images.githubusercontent.com/55352601/114046792-c3afbf00-98a6-11eb-9709-d07d558f12ba.mp4


https://user-images.githubusercontent.com/55352601/114046834-cd392700-98a6-11eb-88d0-411a8ea960dd.mp4

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain both are good. I would prefer the logo one it can be still made better by decreasing the logo size. I think @shades-7 will be able to guide you on this more.

**Comment by arpit456jain** [comment]
ok @vigneshshettyin I will decrease the size of logo.

**Comment by arpit456jain** [comment]
<img width="960" alt="v" src="https://user-images.githubusercontent.com/55352601/114067269-4130fa80-98ba-11eb-969e-0acaca45d82f.png">
@vigneshshettyin  is it ok now ?

**Comment by vigneshshettyin** [comment]
> <img alt="v" width="960" src="https://user-images.githubusercontent.com/55352601/114067269-4130fa80-98ba-11eb-969e-0acaca45d82f.png">
> 
> @vigneshshettyin is it ok now ?

Yup, it's fine @arpit456jain

**Comment by arpit456jain** [comment]
ok @vigneshshettyin making a PR

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly review my PR and kindly  add same labels which are on this issue.
