### ISSUE TITLE
Fix wkhtmltopdf after deployment

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#213]
### **Describe the bug**
For now, pdf is not getting generated after the site is deployed.

### **Expected behavior**
The wkhtmltopdf should be able to generate certificate so that the user should be able to download.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Hey, @ashutoshkrris assigning to you.
