### ISSUE TITLE
[Gssoc'21] Bug in Register

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#217]
### **Describe the bug**
Well I don't know its a bug or not . but I think There is no need of forgot password on register page .
It doesn't make any sense to me.

### **Expected behavior**
It should not be there

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

### **Screenshots**
<img width="960" alt="Untitledefws" src="https://user-images.githubusercontent.com/55352601/114188856-2c5e7080-9967-11eb-9d22-6a104722199a.png">

**Comment by vigneshshettyin** [comment]
That line can be just commented out. @arpit456jain Instead of this you can work on adding a dark mode to the backend dashboard also remove dark mode from the certificate generate page ie (https://cgv.in.net/certify/CGVVIGNOuRW)
https://www.loom.com/share/f4a84947d61b425a9f09c1100eca50aa

**Comment by arpit456jain** [comment]
Ok @vigneshshettyin  i will look into it 
I am closing this issue
