### ISSUE TITLE
[Gssoc'21] bug in contact us form in dark mode

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#228]
### **Describe the bug**
This is section is not visible properly

<img width="960" alt="flask" src="https://user-images.githubusercontent.com/55352601/114556773-a99b2580-9c86-11eb-9d7d-fa9f282fd706.png">
.

### **Expected behavior**
It should be white I think 🤔
### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by shades-7** [comment]
Good catch. Will you like to work on it?

**Comment by arpit456jain** [comment]
> Good catch. Will you like to work on it?

Yes
