### ISSUE TITLE
[Gssoc'21] Adding dark mode in dashboard

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#236]
### Is your feature request related to a problem? Please describe.
I would like to add the dark mode in dashboard 

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by shades-7** [comment]
please add a screenshot of the place where you want to add dark mode

**Comment by arpit456jain** [comment]
<img width="960" alt="dd" src="https://user-images.githubusercontent.com/55352601/114710251-21328880-9d4b-11eb-8bf0-179c0a59c1bf.png">

is it ok ? or should i change the color of side navbar also?

**Comment by arpit456jain** [comment]
> <img alt="dd" width="960" src="https://user-images.githubusercontent.com/55352601/114710251-21328880-9d4b-11eb-8bf0-179c0a59c1bf.png">
> 
> is it ok ? or should i change the color of side navbar also?
 
I think I should not change it color as it is already looks nice other wise all page will be in black

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly review my PR and suitable labels to it as it was really very time taking

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain certificates card has been displaced. Kindly change the location of the toggle button or change the toggle button type to avoid design errors.

**Comment by arpit456jain** [comment]
> Hey, @arpit456jain certificates card has been displaced. Kindly change the location of the toggle button or change the toggle button type to avoid design errors.

@vigneshshettyin I don't understand what you are saying kindly add a screen shot 😅

**Comment by vigneshshettyin** [comment]
> > Hey, @arpit456jain certificates card has been displaced. Kindly change the location of the toggle button or change the toggle button type to avoid design errors.
> 
> @vigneshshettyin I don't understand what you are saying kindly add a screen shot 😅

![114710251-21328880-9d4b-11eb-8bf0-179c0a59c1bf](https://user-images.githubusercontent.com/77713888/114730886-e3d7f600-9d5e-11eb-9277-a0b656fd13af.png)

**Comment by arpit456jain** [comment]
> > > Hey, @arpit456jain certificates card has been displaced. Kindly change the location of the toggle button or change the toggle button type to avoid design errors.
> > 
> > 
> > @vigneshshettyin I don't understand what you are saying kindly add a screen shot 😅
> 
> ![114710251-21328880-9d4b-11eb-8bf0-179c0a59c1bf](https://user-images.githubusercontent.com/77713888/114730886-e3d7f600-9d5e-11eb-9277-a0b656fd13af.png)

Done @vigneshshettyin kindly check pr section
