### ISSUE TITLE
Integrate New Certificate

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#237]
### **Describe the bug**
Since, the old certificate has been ruled out and a new certificate has been used. A lot needs to be changed in the certificate to get it generated dynamically.

### **Expected behavior**
Certificate should be generated dynamically.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
assigned to you. @ashutoshkrris
