### ISSUE TITLE
Add documentation for different cloud platforms

### ISSUE THREAD

**Issue by APratham** [vigneshshettyin/Flask-Generate-Certificate#24]
### Is your feature request related to a problem? Please describe.
The project is currently deployed on Heroku. However, it is possible to deploy it on other cloud platforms too, like GCP, AWS, Digital Ocean, etc. So there is a need to include documentation on how to do that in the repository. 

### Describe how this feature will be useful to our readers.
It will help people to get a better understanding of the project as well as know how to deploy it on the platform of their choice.

<hr/>

Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment and wait for the maintainer or a mentor to assign it to you. Then you can create a PR.

**Comment by mohammedjameel24** [comment]
assign me this task under gssoc

**Comment by APratham** [comment]
@mohammedjameel24 That's wonderful, which platform are you going to write the documentation for? Please write for one platform only (GCP/AWS/Azure/Digital Ocean), not for all of them. It just ensures that others have a chance to participate too

**Comment by mohammedjameel24** [comment]
Aws

**Comment by APratham** [comment]
Great news then Mohammed!

**Comment by mohammedjameel24** [comment]
@APratham 
Do i need to make changes in readme.md file?

**Comment by APratham** [comment]
I would suggest to create another file AWS.md then link to the README file.
You can create the AWS.md file, I can add the links after discussing with
other admins too.

**Comment by APratham** [comment]
@mohammedjameel24  Please update on your progress. As this is a level 2 issue, we can't assign it for longer periods of time. If you are unable to show progress in coming few days, this issue will be unassigned

**Comment by mohammedjameel24** [comment]
Ill publish by evening today if not unassign me

**Comment by APratham** [comment]
That sounds like great news, please complete at the earliest possible. We still need to follow the rules, under which you have up to 2-3 days more until the issue is unassigned.

**Comment by shades-7** [comment]
> Ill publish by evening today if not unassign me

@mohammedjameel24 any updates?

**Comment by mohammedjameel24** [comment]
The aws.md is merged 
Any next documentations ? Let me know

**Comment by shades-7** [comment]
@mohammedjameel24 thank you for your contribution I will close this issue.
