### ISSUE TITLE
Bug in Certificate Generate Page

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#243]
### **Describe the bug**
Certificate is getting generated but not properly using the url : `/certificate/generate`

### **Expected behavior**
The download button should work properly . The QR Image should be rendered.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Yes @ashutoshkrris
