### ISSUE TITLE
User deletion bug

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Flask-Generate-Certificate#249]
### **Describe the bug**
As all tables are related when a user is deleted all groups and certificates under him will also be deleted in order to avoid this implement a pop for confirmation of user deletion.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by ashutoshkrris** [comment]
I can work on this, @vigneshshettyin

**Comment by vigneshshettyin** [comment]
Assigned to you. @ashutoshkrris
