### ISSUE TITLE
Add different badges to the README

### ISSUE THREAD

**Issue by APratham** [vigneshshettyin/Flask-Generate-Certificate#25]
### Is your feature request related to a problem? Please describe.
People can add new badges as per their liking as long as it is related to the project. So for example, a badge that will verify whether the Heroku deployment is working or not and give the current status. There are many ways of creating GitHub README badges

### Describe how this feature will be useful to our readers.
It will help people to get a better understanding of the project.

<hr/>

Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment and wait for the maintainer or a mentor to assign it to you. Then you can create a PR.

**Comment by A-kriti** [comment]
I would like to contribute to this issue as a GSSOC'21 participant.

**Comment by APratham** [comment]
@A-kriti That's great, thanks a lot for helping. Remember that you'll have only 3-4 days to work on a particular issue, as we also need to give others a chance to contribute too. Feel free to discuss your ideas for adding badges here.
