### ISSUE TITLE
Phone number validation 

### ISSUE THREAD

**Issue by ShrutiOmer** [vigneshshettyin/Flask-Generate-Certificate#250]
### **Describe the bug**
In both submit feedback form and contact us form , phone number is not validated. User is able to give character instead of number in phone number and able to submit.

### **Expected behavior**
The message should be displayed to enter the correct phone number it should be valid 10-digit num

### Which Program are you part of?
- [x] GSSOC21
- [] Any other

Please assign this issue to me.

https://user-images.githubusercontent.com/75009990/114977277-0b38db00-9ea5-11eb-9bf1-c07b4cd739b1.mp4

**Comment by shades-7** [comment]
@ShrutiOmer assigned to you.
If possible please add gif of the issue in the issue template

**Comment by ShrutiOmer** [comment]
I have added in issue ,please check it.

**Comment by shades-7** [comment]
> I have added in issue ,please check it.

👍

**Comment by ShrutiOmer** [comment]
When I am deploying project locally, it gives error please help 
![image](https://user-images.githubusercontent.com/75009990/114989468-1136b800-9eb5-11eb-9091-0f34ef0b6779.png)
