### ISSUE TITLE
social app icon in right side

### ISSUE THREAD

**Issue by ShrutiOmer** [vigneshshettyin/Flask-Generate-Certificate#251]
### Is your feature request related to a problem? Please describe.
Instead of having social icons on the top of website, we can add them to right side of page. These will scale out when user hover over it.

### Describe how this feature will be useful to our readers.
Readers can see these icons everytime, they doesn't have to scroll up or down to find the apps.

### Which Program are you part of?
- [x] GSSOC21
- [] Any other

### Additional context
something like this
![icons](https://user-images.githubusercontent.com/75009990/114980404-09bde180-9eaa-11eb-8ace-2a3ae8007764.png)

**Comment by ShrutiOmer** [comment]
Please assign this issue to me.

**Comment by shades-7** [comment]
Please complete previous assigned issues first

**Comment by ShrutiOmer** [comment]
Okk

**Comment by vigneshshettyin** [comment]
Hey, @ShrutiOmer assigning this issue to you.

**Comment by arpit456jain** [comment]
@ShrutiOmer are you working on this?

**Comment by ShrutiOmer** [comment]
Yes, I am working on it.
