### ISSUE TITLE
[Gssoc'21] Replacing confirmation for logout from bootstrap modal to sweet alert

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#253]
I would like to Replace confirmation for logout from bootstrap modal to sweet alert 

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by arpit456jain** [comment]
@vigneshshettyin can I do this?

**Comment by vigneshshettyin** [comment]
Okay

**Comment by arpit456jain** [comment]
@vigneshshettyin its done kindly review my PR
