### ISSUE TITLE
[Gssoc'21] Toggle button is not visible in landing page

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#255]
### **Describe the bug**
 Toggle button is not visible in landing page .
It is visible in login and sign up page
### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by arpit456jain** [comment]
@vigneshshettyin i just notice the dark mode toggle button is not available in landing page but its present in login and signup 

did you intentionally hide that .
@vigneshshettyin please check once if this is happening at your end or not

**Comment by ashutoshkrris** [comment]
Hey @arpit456jain !
Looks like, I did it mistakenly.
The issue was, whenever any error or success message was shown, the cancel symbol was getting overlapped by the toggle button.
So, I decreased the z-index to 0.
Could you please fix this issue of overlapping?

**Comment by arpit456jain** [comment]
> Hey @arpit456jain !
> Looks like, I did it mistakenly.
> The issue was, whenever any error or success message was shown, the cancel symbol was getting overlapped by the toggle button.
> So, I decreased the z-index to 0.
> Could you please fix this issue of overlapping?

@ashutoshkrris  can you please send a video where this issue is occurring I will surely try to fix it

**Comment by ashutoshkrris** [comment]
> > Hey @arpit456jain !
> > Looks like, I did it mistakenly.
> > The issue was, whenever any error or success message was shown, the cancel symbol was getting overlapped by the toggle button.
> > So, I decreased the z-index to 0.
> > Could you please fix this issue of overlapping?
> 
> @ashutoshkrris can you please send a video where this issue is occurring I will surely try to fix it

If you just change the z-index to the previous value..and open a page where toggle button is there and a notification shows up, you can see the issue

**Comment by arpit456jain** [comment]
> > > Hey @arpit456jain !
> > > Looks like, I did it mistakenly.
> > > The issue was, whenever any error or success message was shown, the cancel symbol was getting overlapped by the toggle button.
> > > So, I decreased the z-index to 0.
> > > Could you please fix this issue of overlapping?
> > 
> > 
> > @ashutoshkrris can you please send a video where this issue is occurring I will surely try to fix it
> 
> If you just change the z-index to the previous value..and open a page where toggle button is there and a notification shows up, you can see the issue

@ashutoshkrris on the landing page ?

**Comment by arpit456jain** [comment]
@ashutoshkrris I am the one Who added  this dark mode and toggle button but I am unable to find where its creating issue @vigneshshettyin kindly help us out

**Comment by vigneshshettyin** [comment]
Even I check it some issue with z-index I tried fixing it but couldn't https://www.loom.com/share/db360fd684fa43e985e2091e74d75e3d
cc @ashutoshkrris @arpit456jain

**Comment by arpit456jain** [comment]
@vigneshshettyin its because its position is absolute I had try  also a lot and put it in navbar after login and its looking like this

https://user-images.githubusercontent.com/55352601/115061271-972f1f00-9f06-11eb-8d2c-8dd963674ca4.mp4

**Comment by vigneshshettyin** [comment]
Cool, make pr for it @arpit456jain

**Comment by arpit456jain** [comment]
ok @vigneshshettyin 2 mins
