### ISSUE TITLE
Export contact response to csv

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Flask-Generate-Certificate#262]
### Is your feature request related to a problem? Please describe.
Option to export all contact response to csv  

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by devRawnie** [comment]
I would like to work on this, but I need help setting the project locally. After installing the project locally I am unable to make an account as it says failure in sending email verification.

**Comment by vigneshshettyin** [comment]
> I would like to work on this, but I need help setting the project locally. After installing the project locally I am unable to make an account as it says failure in sending email verification.

Yeah sure, Please check ur shell confirmation link will be printed there as well. @devRawnie

**Comment by devRawnie** [comment]
I created an account using the admin_email provided in the email file. Then while registering i pasted the link in the browser, prepending the path with localhost:5000. I was able to login successfully but it is not the admin panel. How do I get in the admin panel?

**Comment by devRawnie** [comment]
Further, when I goto route /certificate/generate, it returns an error "User is not defined"

**Comment by vigneshshettyin** [comment]
> I created an account using the admin_email provided in the email file. Then while registering i pasted the link in the browser, prepending the path with localhost:5000. I was able to login successfully but it is not the admin panel. How do I get in the admin panel?

Hey, @devRawnie admin panel is `/dashboard`

**Comment by vigneshshettyin** [comment]
> Further, when I goto route /certificate/generate, it returns an error "User is not defined"

Hey, @devRawnie have you followed all steps mentioned in (https://github.com/vigneshshettyin/Flask-Generate-Certificate/blob/main/docs/INSTALLATION.md) ie including creating a new file called .env

**Comment by devRawnie** [comment]
![Screenshot from 2021-04-19 12-25-05](https://user-images.githubusercontent.com/43227329/115193932-6586a580-a10a-11eb-9d34-ee250ab20fb4.png)
![Screenshot from 2021-04-19 12-23-48](https://user-images.githubusercontent.com/43227329/115193949-691a2c80-a10a-11eb-8820-cde2790cad97.png)
 Yes I created the .env file. Is this the dashboard for admin panel or a normal user?

**Comment by vigneshshettyin** [comment]
Hey, @devRawnie download and install DB Browser (https://sqlitebrowser.org/dl/) in the user table there is a field called is_admin make it 1 then you will have admin privileges.

**Comment by devRawnie** [comment]
Hi @vigneshshettyin . Thank you for your help so far. I am able to access the Admin panel now. Could you please tell what are the further steps for contributing?

**Comment by devRawnie** [comment]
Specifically for creating and verifying certificates. As you can see the user table has a field {user.name}, however, the same error occurs when i go to /certificate/generate.
![Screenshot from 2021-04-19 13-05-00](https://user-images.githubusercontent.com/43227329/115198612-e1cfb780-a10f-11eb-9375-6f895c3d2521.png)

![Screenshot from 2021-04-19 13-03-28](https://user-images.githubusercontent.com/43227329/115198427-aa610b00-a10f-11eb-9561-cd5917ba5c26.png)

**Comment by vigneshshettyin** [comment]
Hey, @devRawnie I just spotted that bug. 
![Capture](https://user-images.githubusercontent.com/77713888/115204246-e6976a00-a115-11eb-9c85-6a2543a45a52.PNG)

**Comment by vigneshshettyin** [comment]
> Hey, @devRawnie I just spotted that bug.
> ![Capture](https://user-images.githubusercontent.com/77713888/115204246-e6976a00-a115-11eb-9c85-6a2543a45a52.PNG)

I have committed it. Just pull once the bug will be fixed automatically. @devRawnie

**Comment by arpit456jain** [comment]
@vigneshshettyin can I work on this issue

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin can I work on this issue

Yes

**Comment by arpit456jain** [comment]
@vigneshshettyin i had done this making a PR

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/115275003-dfe11500-a15e-11eb-951b-5f3ae55aefae.mp4

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly review my PR and add same labels to it

**Comment by vigneshshettyin** [comment]
Yup, will merge it asap @arpit456jain
