### ISSUE TITLE
Export all newsletter response

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Flask-Generate-Certificate#263]
### Is your feature request related to a problem? Please describe.
Option to export all newsletter response to csv  

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by ashutoshkrris** [comment]
I would like to work on this issue.

**Comment by arpit456jain** [comment]
@ashutoshkrris if you are working on #265 

can i work on this issue .

**Comment by vigneshshettyin** [comment]
> I would like to work on this issue.

Yes, @ashutoshkrris

**Comment by vigneshshettyin** [comment]
> @ashutoshkrris if you are working on #265
> 
> can i work on this issue .

Hey, the issue will be assigned on first come first serve basis @arpit456jain

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain assigning to you.

**Comment by arpit456jain** [comment]
@vigneshshettyin dont't take it wrong actually by mistake i write 263 intead of 262 but i have corrected my mistake .
