### ISSUE TITLE
Feedback response to csv

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Flask-Generate-Certificate#264]
### Is your feature request related to a problem? Please describe.
Option to export all feedback response to csv

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by arpit456jain** [comment]
@vigneshshettyin I would like to give it a try

**Comment by vigneshshettyin** [comment]
Yes, you can @arpit456jain

**Comment by arpit456jain** [comment]
> Yes, you can @arpit456jain

@vigneshshettyin which data base is used in project as in readme.dm there are two types of databases mentioned 
postgresql and sqlite 
and i am searching on google for past 1 hour how to export data to csv but mostly it is related to mysql 

@vigneshshettyin  help  me out

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/115215913-9c1bea80-a121-11eb-9b7a-3ee832212962.mp4

@vigneshshettyin is it ok ??

**Comment by arpit456jain** [comment]
<img width="960" alt="cv" src="https://user-images.githubusercontent.com/55352601/115216536-3845f180-a122-11eb-9611-f34190a78e9c.png">

@vigneshshettyin  previously one blank line is present after every row now it is solved also . May I create a PR for this?

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain that's great. But I want the file to be downloaded when the admin triggers the URL. Also, have you managed the state where if there are no feedback responses? If there are no feedback responses then display an error notification either using sweet alert or simple notify.

**Comment by arpit456jain** [comment]
> Hey, @arpit456jain that's great. But I want the file to be downloaded when the admin triggers the URL. Also, have you managed the state where if there are no feedback responses? If there are no feedback responses then display an error notification either using sweet alert or simple notify.

yes @vigneshshettyin I handle the 0 feedback condition  but how to check user is admin or not ?

**Comment by arpit456jain** [comment]
<img width="960" alt="fd" src="https://user-images.githubusercontent.com/55352601/115236600-2c195e80-a139-11eb-87c3-330d16640b73.png">

**Comment by arpit456jain** [comment]
@vigneshshettyin I just have to add condition for admin kindly help me in this

**Comment by arpit456jain** [comment]
> @vigneshshettyin I just have to add condition for admin kindly help me in this

done @vigneshshettyin this is also done finally.

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin I just have to add a condition for admin kindly help me in this

Without the user being authenticated we can't know if he is an admin or a normal user. I suggest you first login into the dashboard go to the contact section add a button top there to download the response in CSV. These change I suggest you do first. For checking, if a user is admin or not it's very simple just check if current_user.is_admin==1 if true download else display an error message. @arpit456jain

**Comment by arpit456jain** [comment]
![16188368554495107660103231907097](https://user-images.githubusercontent.com/55352601/115239524-7a7c2c80-a13c-11eb-9379-0553eb4388b5.jpg)

**Comment by arpit456jain** [comment]
@vigneshshettyin  is_admin is not working 
I try to add a line @admin_required 
 It is redirecting me this page
![16188370891768629152168664940254](https://user-images.githubusercontent.com/55352601/115240081-0726ea80-a13d-11eb-8438-51979af33409.jpg)

**Comment by ashutoshkrris** [comment]
> @vigneshshettyin is_admin is not working
> I try to add a line @admin_required
> It is redirecting me this page
> ![16188370891768629152168664940254](https://user-images.githubusercontent.com/55352601/115240081-0726ea80-a13d-11eb-8438-51979af33409.jpg)
it's because you are not admin

**Comment by arpit456jain** [comment]
@ashutoshkrris when i said is_admin is not working i am talking about the error user obj has no attribute is admin as you can see in pic above

**Comment by ashutoshkrris** [comment]
> @ashutoshkrris when i said is_admin is not working i am talking about the error user obj has no attribute is admin as you can see in pic above 

I had already created a decorator `@admin_required` that acts as a middleware to check if the current user is admin.
If you are an admin, it will work without any issue
If you aren't, you will be redirected to the above 405 error page.

**Comment by arpit456jain** [comment]
> > @ashutoshkrris when i said is_admin is not working i am talking about the error user obj has no attribute is admin as you can see in pic above
> 
> I had already created a decorator `@admin_required` that acts as a middleware to check if the current user is admin.
> If you are an admin, it will work without any issue
> If you aren't, you will be redirected to the above 405 error page.

Ok thanks @ashutoshkrris

**Comment by arpit456jain** [comment]
@ashutoshkrris can you please help me with how to login as admin

**Comment by ashutoshkrris** [comment]
Can we talk over discord? @arpit456jain
