### ISSUE TITLE
Export all certificates under a specific group to csv

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Flask-Generate-Certificate#265]
### Is your feature request related to a problem? Please describe.
option to export all certificates under a specific group to csv

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by ashutoshkrris** [comment]
I would like to work on this issue.

**Comment by vigneshshettyin** [comment]
> I would like to work on this issue.

Yes @ashutoshkrris
