### ISSUE TITLE
Import certificates from csv

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Flask-Generate-Certificate#266]
### Is your feature request related to a problem? Please describe.
Option to import all certificates from a CSV file 

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by ashutoshkrris** [comment]
Hey @vigneshshettyin I want to work on this issue

**Comment by vigneshshettyin** [comment]
Yup, @ashutoshkrris
