### ISSUE TITLE
Update all contributors to the website. 

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Flask-Generate-Certificate#27]
### Is your feature request related to a problem? Please describe.
![Screenshot 2021-03-10 235256](https://user-images.githubusercontent.com/77713888/110678128-f7da8600-81fb-11eb-92c5-13d63fb30d6b.png)
Select unique contributors and add their photo and Github link to the app.

### Describe the solution you'd like
To get a list of all contributors use GitHub API (https://api.github.com/repos/vigneshshettyin/Flask-Generate-Certificate/commits). Select unique contributors. Profile photo (avatar_url) & Profile Link (html_url) is available in the JSON response obtained.

**Comment by ashutoshkrris** [comment]
I would like to work on this issue

**Comment by vigneshshettyin** [comment]
Always a yes for you.

**Comment by vigneshshettyin** [comment]
Hey @ashutoshkrris  

The present script which you have written will get all contributors dictionary. Make changes such it should continue if committer usernames are vigneshshettyin, APratham, rex_divakar, shades-7 as their details is already there in the mentor section.

**Comment by ashutoshkrris** [comment]
Yes @vigneshshettyin , I have got it covered now

**Comment by vigneshshettyin** [comment]
> Yes @vigneshshettyin , I have got it covered now

Great @ashutoshkrris

**Comment by vigneshshettyin** [comment]
@ashutoshkrris it is not taking all contributors. Check it again

**Comment by ashutoshkrris** [comment]
Sure, I'm looking into it @vigneshshettyin

**Comment by vigneshshettyin** [comment]
Cool

**Comment by vigneshshettyin** [comment]
As the present api is not getting all contributors . I have found a new API for it (https://api.github.com/repos/vigneshshettyin/Flask-Generate-Certificate/contributors?per_page=1000). Kindly update the same @ashutoshkrris

**Comment by ashutoshkrris** [comment]
Sure @vigneshshettyin 
I'll do it
