### ISSUE TITLE
Add a link in the dropdown menu on the main page to the dashboard

### ISSUE THREAD

**Issue by devRawnie** [vigneshshettyin/Flask-Generate-Certificate#270]
### Is your feature request related to a problem? Please describe.
When the user is logged in and on the index.html page, there is no link to re-direct the user to the dashboard.

### Describe the solution you'd like
Under the dropdown menu on index.html page, add a link to the dashboard

### Which Program are you part of?

- [x] GSSOC21

**Comment by vigneshshettyin** [comment]
Yes, @devRawnie assigning to you.
