### ISSUE TITLE
Date of Certification not showing up in Certificate verify Page

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#279]
### **Describe the bug**
The Date of Certification is not showing up on Certificate Verify Page. This is a minor bug. Also, I would like to add a button which will redirect the user to his certificate directly.

### **To Reproduce**
1. Go to 'Verify Certificate Page'
2. Click on 'Verify'
3. Enter a Valid Certificate Number.

### **Expected behavior**
Date of certification should be visible.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

### **Screenshots**
![Screenshot (329)](https://user-images.githubusercontent.com/47353498/115551542-decbf700-a2c8-11eb-909a-2a81fd504d8f.png)

**Comment by vigneshshettyin** [comment]
Yeah, do fix it. @ashutoshkrris
