### ISSUE TITLE
No Need for Two Separate Certificate Verify Template Page

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#281]
### **Describe the bug**
As of now, we have two separate html pages - one for showing the error if a certificate is not found and another for showing certificate details if a certificate is found.

### **Expected behavior**
Instead of two separate pages, we can have just one page and we can achieve the same task

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Yup, assigning to you. @ashutoshkrris
