### ISSUE TITLE
Changes in Side bar

### ISSUE THREAD

**Issue by Sukriti-sood** [vigneshshettyin/Flask-Generate-Certificate#287]
In Mobile View ,On sliding from left side should open Sidebar , it gives good user experience.

**Comment by vigneshshettyin** [comment]
Okay @Sukriti-sood

**Comment by APratham** [comment]
@Sukriti-sood Can you please let us know if there is an update? If you need help you can ask on Discussions or on the Discord server

**Comment by Sukriti-sood** [comment]
Sorry @APratham I will update it in a day or two.

**Comment by Sukriti-sood** [comment]
Hello Mentors  Currently I am unable to implement it , I have started discussion for same .

**Comment by shades-7** [comment]
what are the problems you are facing?
