### ISSUE TITLE
bug in Dashboard

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#288]
### **Describe the bug**

There are some bugs in Dash Board in Dark mode

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly assign  me this.

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin kindly assign  me this.
> 
> 
> 

Yup, assigning to you @arpit456jain

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/115700784-adb0fc80-a384-11eb-97e4-1eb89e6c3de3.mp4

<img width="960" alt="bug in dm" src="https://user-images.githubusercontent.com/55352601/115700958-e18c2200-a384-11eb-9c9f-2c6d1c96661b.png">

**Comment by arpit456jain** [comment]
@vigneshshettyin is that fine ??

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin is that fine ??

Yup @arpit456jain

**Comment by arpit456jain** [comment]
ok making a PR for this
