### ISSUE TITLE
bug in Certificate Generation page

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#290]
### **Describe the bug**
bug in Certificate Generation page

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by arpit456jain** [comment]
@vigneshshettyin assign me this

i have solved the all the bugs 

and 1 question : on certificate generation page there were no others section like prices services and etc but in a tag linke is given as #services that's why they are not working  should i change them to /#services by doing this user will redirect to home page and then services section same for others also

**Comment by vigneshshettyin** [comment]
Okay

**Comment by vigneshshettyin** [comment]
> Okay

@arpit456jain
