### ISSUE TITLE
Bug in View Groups

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#291]
### **Describe the bug**
Admin is not able to view all the groups

### **To Reproduce**
1. Go to 'Dashboard'
2. Click on 'List Groups'
3. See error

### **Expected behavior**
Admin should be able to view all groups and all the certificates within that group.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Okay @ashutoshkrris
