### ISSUE TITLE
Add documentation for different cloud platforms | Azure

### ISSUE THREAD

**Issue by APratham** [vigneshshettyin/Flask-Generate-Certificate#303]
### Is your feature request related to a problem? Please describe.
The project is currently deployed on Heroku. However, it is possible to deploy it on other cloud platforms too, like GCP, AWS, Digital Ocean, etc. So there is a need to include documentation on how to do that in the repository. 

### Describe how this feature will be useful to our readers.
It will help people to get a better understanding of the project as well as know how to deploy it on the platform of their choice.

<hr/>

Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment and wait for the maintainer or a mentor to assign it to you. Then you can create a PR.

**Comment by 1vivekanand** [comment]
I would like to work on this issue. Just need one clarity that I have to make documentation on how to deploy apps on all the above three or any of the three ?

**Comment by shades-7** [comment]
You have to make documentation on azure

**Comment by APratham** [comment]
@1vivekanand We have already added documentation for AWS, so we want it for other platforms. #302 and #304 are also related, only made for different platforms

**Comment by 1vivekanand** [comment]
Got it, please assign it to me

**Comment by APratham** [comment]
Done 🚀. Let's write some great documentation

**Comment by shades-7** [comment]
any update @1vivekanand

**Comment by 1vivekanand** [comment]
Actually I am busy with my college exams . Not much progress till yet...I will update you about the  progress within 3 days

**Comment by subhangi2731** [comment]
@shades-7 @vigneshshettyin can i please work on this

**Comment by vigneshshettyin** [comment]
> @shades-7 @vigneshshettyin can i please work on this

Yes you can @subhangi2731
