### ISSUE TITLE
Add documentation for different app platforms

### ISSUE THREAD

**Issue by APratham** [vigneshshettyin/Flask-Generate-Certificate#304]
### Is your feature request related to a problem? Please describe.
The project is currently deployed on Heroku. However, it is possible to deploy it on app platforms like Digital Ocean/Heroku, etc. So there is a need to include documentation on how to do that in the repository. 

### Describe how this feature will be useful to our readers.
It will help people to get a better understanding of the project as well as know how to deploy it on the platform of their choice.

<hr/>

Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment and wait for the maintainer or a mentor to assign it to you. Then you can create a PR.

**Comment by meenaljain0303** [comment]
I would like to work on this issue.

**Comment by shades-7** [comment]
Go ahead, assigned to you @meenaljain0303

**Comment by shades-7** [comment]
any update @meenaljain0303

**Comment by meenaljain0303** [comment]
I am still working on it, will be done by tuesday sir.

**Comment by meenaljain0303** [comment]
Having Difficulties, sorry.

**Comment by subhangi2731** [comment]
@shades-7 I can work on this please assign me will send a pr today
