### ISSUE TITLE
I think the blue boundary on the "send message " button should not be there.

### ISSUE THREAD

**Issue by barsha119** [vigneshshettyin/Flask-Generate-Certificate#31]
### Is your feature request related to a problem? Please describe.
yes , I think the blue boundary around the send message button in the bottom section of the page doesn't look good as it doesn't match with other button.
### Describe the solution you'd like
I want to remove the blue boundary 

### Additional context
please assign me this issue under gssoc'21 

<hr/>

Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.  
If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.  
Then you can directly start working on the issue.

**Comment by ashutoshkrris** [comment]
If you are assigned the issue, please also remove the boundary from Pay With Razorpay Button (when you click on Pay Button in Pricing Section). Also could you please take care of the spacing between Get Started and Contact Us buttons in mobile version?

**Comment by vigneshshettyin** [comment]
I'll assign you the issue but do all the changes which @ashutoshkrris has mentioned. @barsha119

**Comment by barsha119** [comment]
> If you are assigned the issue, please also remove the boundary from Pay With Razorpay Button (when you click on Pay Button in Pricing Section). Also could you please take care of the spacing between Get Started and Contact Us buttons in mobile version?

Sure, I will remove the spacing between  Get Started and Contact Us buttons in mobile also.

**Comment by barsha119** [comment]
How will I contact you (@vigneshshettyin and @ashutoshkrris ) if I am having some doubts or problem?

**Comment by vigneshshettyin** [comment]
> How will I contact you (@vigneshshettyin and @ashutoshkrris ) if I am having some doubts or problem?
> 

You can start a discussion and tag us. We will respond as soon as possible.

**Comment by barsha119** [comment]
> > How will I contact you (@vigneshshettyin and @ashutoshkrris ) if I am having some doubts or problem?
> 
> You can start a discussion and tag us. We will respond as soon as possible.

@vigneshshettyin actually I am having problem in downloading the requirement.txt file

**Comment by ashutoshkrris** [comment]
> > > How will I contact you (@vigneshshettyin and @ashutoshkrris ) if I am having some doubts or problem?
> > 
> > 
> > You can start a discussion and tag us. We will respond as soon as possible.
> 
> @vigneshshettyin actually I am having problem in downloading the requirement.txt file

Please create and a discussion and we can discuss the problem over there.
