### ISSUE TITLE
QR Based Certificate generator

### ISSUE THREAD

**Issue by shantamsultania** [vigneshshettyin/Flask-Generate-Certificate#32]
I think adding QR based certificate Generation feature can also benefit the Certificate receivers

Think of a scenario you have organized a large event here you cannot add things like make each and everyone fill a form or something here you can add a QR based Certificate generator.

**Comment by vigneshshettyin** [comment]
Cool feature, we can try to implement this. Can you work on this ??

**Comment by shantamsultania** [comment]
yes let me finish the issue that I mentioned earlier than will start working on this too

**Comment by shantamsultania** [comment]
sorry i by mistakenly clicked close issue silly me 😜

**Comment by shades-7** [comment]
> yes let me finish the issue that I mentioned earlier than will start working on this too

@shantamsultania that will be great :+1:

**Comment by ashutoshkrris** [comment]
I can also work on this issue, let me know if it's available.

**Comment by shades-7** [comment]
@ashutoshkrris keep updating the progress 
All the best 👍

**Comment by asaxena012** [comment]
Hey, I have worked on QR Code generation using JavaScript. 

Here is my project [demo](https://www.youtube.com/watch?v=nlYsU49MUnE)

Please let me know if I can help with this issue. Thanks.

**Comment by ashutoshkrris** [comment]
> Hey, I have worked on QR Code generation using JavaScript.
> 
> Here is my project [demo](https://www.youtube.com/watch?v=nlYsU49MUnE)
> 
> Please let me know if I can help with this issue. Thanks.

I'm on it @asaxena012 .
Will let you know if I face any issue
