### ISSUE TITLE
Some Enhancement

### ISSUE THREAD

**Issue by Sukriti-sood** [vigneshshettyin/Flask-Generate-Certificate#326]
### I don't know it is relevant or not , but I find that space between social links and sections should be less.
![CGV _ Online Cer (1)](https://user-images.githubusercontent.com/55010599/116903902-ae864000-ac5a-11eb-88dd-43a7ac96a81e.png)

###  this overlapping..

![CGV _ Online Cer](https://user-images.githubusercontent.com/55010599/116903922-b3e38a80-ac5a-11eb-9a80-1f6acf70a4da.png)

### Overlapping of dark mode button
![Screenshot_2021_0504_083735](https://user-images.githubusercontent.com/55010599/116956938-23d22f00-acb4-11eb-995d-e6c8671f764a.png)

**Comment by vigneshshettyin** [comment]
Yup, your points are valid those should be fixed. You can work on it. @Sukriti-sood 

Thanks for pointing out 😄
