### ISSUE TITLE
Add a bulk Certificate Mail sender for the Admin 

### ISSUE THREAD

**Issue by shantamsultania** [vigneshshettyin/Flask-Generate-Certificate#33]
thinking of adding a Bulk certificate sender for the Admin with the help of which he/she can share multiple certificates to multiple people @vigneshshettyin what are your points on this.

**Comment by vigneshshettyin** [comment]
Yup, you can work on it.

**Comment by APratham** [comment]
@shantamsultania  Please update on your progress. As this is a level 3 issue, we can assign it for only a select period of time. If you are unable to show progress in coming 2-3 days, this issue will be unassigned

**Comment by shades-7** [comment]
@shantamsultania any updates?

**Comment by shantamsultania** [comment]
hey, @shades-7 made a python program for adding a Bulk mailer need to integrate it with your UI it will take me sometime around 3-4 days I think will be able to wrap up by Monday. sorry for slow progress busy with office work so

**Comment by shades-7** [comment]
@shantamsultania Thanks for the update, its fine to take your time but keep updating every second day :+1:

**Comment by shantamsultania** [comment]
ok will do

**Comment by shantamsultania** [comment]
hey guys sorry for this but due to some issue and sudden work in the office I had to leave this issue really sorry to waste your time please assign someone else this issue I know it was level 3 and I also wrote the code but cannot make the integrations with your UI if anyone else wants to work on this I can share him/her my half code. @shades-7 , @vigneshshettyin @APratham

**Comment by APratham** [comment]
Closing this issue until further notice
