### ISSUE TITLE
Setup github actions to beautify the code when pr is raised. 

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Flask-Generate-Certificate#331]
### Is your feature request related to a problem? Please describe.
Create a GitHub action to beautify the code automatically when pr is raised 

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by Mohitmadhav** [comment]
@vigneshshettyin can I work on this issue please?

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin can I work on this issue please?
> 

Yes @Mohitmadhav assigning this issue to you

**Comment by Mohitmadhav** [comment]
@vigneshshettyin how about this ? : https://github.com/peter-evans/autopep8

**Comment by Mohitmadhav** [comment]
> @vigneshshettyin how about this ? : https://github.com/peter-evans/autopep8

Or I could just go with Prettier.

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin how about this ? : https://github.com/peter-evans/autopep8

Yup, this is fine prettier sometimes causes errors. @Mohitmadhav

**Comment by Mohitmadhav** [comment]
@vigneshshettyin please check the PR

**Comment by vigneshshettyin** [comment]
Merged(https://github.com/vigneshshettyin/Flask-Generate-Certificate/pull/366)

**Comment by Mohitmadhav** [comment]
Thank you! now I'm deleting the branch
