### ISSUE TITLE
Greeting Workflow Not Working

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Flask-Generate-Certificate#332]
### **Describe the bug**
Github actions were set to greet contributors when an issue or pr is raised. (https://github.com/vigneshshettyin/Flask-Generate-Certificate/blob/main/.github/workflows/greetings.yml) . Kindly fix this

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by arpit456jain** [comment]
<img width="960" alt="greeting" src="https://user-images.githubusercontent.com/55352601/116994229-1178e500-acf6-11eb-9af6-055387ee19c3.png">

@vigneshshettyin I have tried this issue on one of my repo its working fine as it creates a greeting but i don't understand why its  adding labels of gssoc and proposal to it😅😅😅

**Comment by vigneshshettyin** [comment]
No clue should check the script @arpit456jain. Please share the YAML file.

**Comment by arpit456jain** [comment]
name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: Karthik-Nayak98/Greeting-action@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        issue_message: 'Hello @${{github.actor}}, <br>
                        Thank you for opening an issue. :partying_face: <br>
                        To get assigned to this particular issue please wait for <b>maintainers</b><br>
                       '
        PR_message:
                      '<h1> :partying_face: Congratulations :tada: </h1>:pray:
                      Thank you @${{github.actor}} for taking out your time and contributing to our project. Our team will now review this and if everything looks good it will be merged.'

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain you can make pr for this.

**Comment by arpit456jain** [comment]
yes making the PR
