### ISSUE TITLE
Enhacement in show password 

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#338]
Enhacement in show password 
<img width="960" alt="eye" src="https://user-images.githubusercontent.com/55352601/117148129-92f27500-add3-11eb-82c3-3200d1449576.png">

**Comment by vigneshshettyin** [comment]
Okay @arpit456jain

**Comment by arpit456jain** [comment]
@vigneshshettyin  may I had this feature in sign up too ?
