### ISSUE TITLE
update the README on how to setup the app in local env 

### ISSUE THREAD

**Issue by shades-7** [vigneshshettyin/Flask-Generate-Certificate#34]
### What part(s) of the article would you like to see updated?

https://github.com/vigneshshettyin/Flask-Generate-Certificate#how-to-use-

### Additional information
Make it clear, precise, and beginner-friendly

**Comment by Nik-09** [comment]
I would to like to update the README. please assign me @shades-7. Thanks.

**Comment by shades-7** [comment]
Go ahead @Nik-09 it's yours 🤗

**Comment by APratham** [comment]
@Nik-09 Please update on your progress. As this is a level 2 issue, we can't assign it for longer periods of time. If you are unable to show progress in coming 2-3 days, this issue will be unassigned

**Comment by iamansoni** [comment]
Is this issue still need to be addressed? If yes, you can assign it to me. 
I would like to work on this task!

**Comment by APratham** [comment]
@iamansoni You'll have to wait for 2 more days. If it is unassigned we can assign it back to you. Then you can start working on it

**Comment by shades-7** [comment]
@Nik-09 any update?

**Comment by shades-7** [comment]
@Nik-09 since you have not given any update, I have to unassign you. sorry

**Comment by devansh-07** [comment]
@shades-7 I'd like to work on this issue. Can you please assign it to me?

**Comment by shades-7** [comment]
@devansh-07 it's yours but keep updating us
