### ISSUE TITLE
Pop-up Profile page template

### ISSUE THREAD

**Issue by TrojanTarun** [vigneshshettyin/Flask-Generate-Certificate#340]
### Is your feature request related to a problem? Please describe.
User's unable to see or customize profile on the dashboard.

I want to add a pop-up profile page .

**Comment by vigneshshettyin** [comment]
Hey, @TrojanTarun assigning this issue to you.

**Comment by shades-7** [comment]
@TrojanTarun any update

**Comment by TrojanTarun** [comment]
> @TrojanTarun any update

Hello @shades-7 ,
I have completed the pop-profile page.
Will make a PR today for this.
