### ISSUE TITLE
Add project logo on the top README 

### ISSUE THREAD

**Issue by shades-7** [vigneshshettyin/Flask-Generate-Certificate#35]
### What part(s) of the article would you like to see updated?

https://github.com/vigneshshettyin/Flask-Generate-Certificate#certificate-generation-and-verification-system

### Additional information
Download the logo from here
https://drive.google.com/file/d/1tQ3EenDhq6BSstj60BGKfiQs-LIafFi3/view?usp=sharing

**Comment by ashutoshkrris** [comment]
@shades-7 
I have made a PR for this issue.

**Comment by shades-7** [comment]
> @shades-7
> I have made a PR for this issue.

Hello @ashutoshkrris don't reply in hsate, first of all see what image I am asking to add to read me file. 
@vigneshshettyin this is different from what @ashutoshkrris has submitted PR for another issue this is different one please open this issue
