### ISSUE TITLE
Adding React to the project

### ISSUE THREAD

**Issue by subhangi2731** [vigneshshettyin/Flask-Generate-Certificate#358]
Add React for front-end development. Setting up a frontend folder with boilerplate code.

**Comment by vigneshshettyin** [comment]
I didn't get you can you explain your issue in brief. @subhangi2731

**Comment by subhangi2731** [comment]
I will create a frontend folder and build a react app for the project. Does this sound good?

**Comment by vigneshshettyin** [comment]
Hey, @subhangi2731 yup you can do that it will be useful when we move our application to the rest framework for GraphQL. Please split up the whole dev process into multiple issues so, that you get the necessary points for your contribution. 

Happy Coding!!

**Comment by vigneshshettyin** [comment]
Hey, @subhangi2731 assigning this issue to you.

**Comment by shades-7** [comment]
hello, @subhangi2731 are you talking about moving the frontend part of a project to react?
if yes, can you please provide a brief on how are you planning to do so, since moving a project to another framework or library need lots of planning.

**Comment by subhangi2731** [comment]
hey @shades-7 I will create a frontend folder and set the react app and yes I will be building from scratch the homepage for react application

**Comment by shades-7** [comment]
@subhangi2731 that will be a great initiative.
start doing that, we will split this issue into smaller parts once you create the folder and basic routing.
