### ISSUE TITLE
Creating a homepage and adding content about existing routes

### ISSUE THREAD

**Issue by subhangi2731** [vigneshshettyin/Flask-Generate-Certificate#359]
I will create a homepage and add content about existing routes.

**Comment by subhangi2731** [comment]
please assign me this @vigneshshettyin

**Comment by vigneshshettyin** [comment]
Hey, @subhangi2731 is this issue related to the current app or the new app frontend which you are going to build.

**Comment by subhangi2731** [comment]
@vigneshshettyin It will be totally a new one as I will be building it from scratch please assign me
