### ISSUE TITLE
Category Filter

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#367]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
We don't have any category feature here. An organisation may require to generate certificates on the basis of different categories (course completion, internships, etc)

### Describe the solution you'd like
We can have a separate category table for it and an organization can create it for themselves.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Hey, @ashutoshkrris assigning this issue to you.
