### ISSUE TITLE
bug in home page

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#373]
### **Describe the bug**
section after header is looking little bit odd it should take 100% height and width after all its home section
and it is having some margin from left also

see this

<img width="960" alt="home" src="https://user-images.githubusercontent.com/55352601/118239458-70d5b280-b4b7-11eb-81f9-00794501cd93.png">

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by arpit456jain** [comment]
@vigneshshettyin please assign me if its  really a bug

**Comment by techpkd123** [comment]
you can assign this to me if not assigned yet

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin please assign me if its really a bug

Hey, in order to encourage new contributors this issue will be assigned to @techpkd123

**Comment by vigneshshettyin** [comment]
> you can assign this to me if not assigned yet

Yes, assigning this issue to you. @techpkd123

**Comment by arpit456jain** [comment]
@vigneshshettyin I had already started working on it but its okay...
carry on @techpkd123  .

**Comment by arpit456jain** [comment]
@vigneshshettyin mean while can I create a issue for adjusting the toggle button since due to merging some PRs  it shifted down a little bit

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin mean while can I create a issue for adjusting the toggle button since due to merging some PRs it shifted down a little bit

Yup, @arpit456jain you can.

**Comment by techpkd123** [comment]
yes sir working on it

**Comment by arpit456jain** [comment]
@techpkd123 any update ?
@vigneshshettyin can i make a PR for this

**Comment by vigneshshettyin** [comment]
Yes, you can @arpit456jain
