### ISSUE TITLE
Grammatical Errors in Readme

### ISSUE THREAD

**Issue by RubenFalcao14** [vigneshshettyin/Flask-Generate-Certificate#374]
![IMG_20210514_132810.jpg](https://user-images.githubusercontent.com/79042516/118240126-3fa9b200-b4b8-11eb-90f2-a71076518111.jpg)

I have found a grammatical error in the Readme , I believe the underlined word should be use and not user. I would love to fix it.

### Which Program are you part of?
- [x] GSSOC21

**Comment by vigneshshettyin** [comment]
Hey, @RubenFalcao14 I'll assign this issue to you I want to make some more changes in the readme. May be aligning badges or adding new badges or maybe styling them @RubenFalcao14

**Comment by RubenFalcao14** [comment]
Hii , @vigneshshettyin  could you please tell me where I can find the code for the labels .
Thank You.

**Comment by vigneshshettyin** [comment]
> Hii , @vigneshshettyin could you please tell me where I can find the code for the labels .
> Thank You.

Hey, @RubenFalcao14 you can find some badges here (https://github.com/alexandresanlim/Badges4-README.md-Profile). You will find more search for it.
