### ISSUE TITLE
Setting up Eslint in the project and making code prettier

### ISSUE THREAD

**Issue by subhangi2731** [vigneshshettyin/Flask-Generate-Certificate#377]
hey @vigneshshettyin please assign me I will lint the code and set up Eslint

**Comment by vigneshshettyin** [comment]
> hey @vigneshshettyin please assign me I will lint the code and set up Eslint

Okay, @subhangi2731 assigning this issue to you. Hey, @shades-7, please do guide @subhangi2731 as she will be working on react frontend part.
