### ISSUE TITLE
Dynamic Certificate Data

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#378]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
The certificate data is static to some extent.

### Describe the solution you'd like
It can be made completely dynamic.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Hey, @ashutoshkrris assigning this issue to you.
