### ISSUE TITLE
Certificate API

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#388]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
There is no certificate API.

### Describe the solution you'd like
We can implement certificate API that returns certificates on the basis of categories

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Hey, @ashutoshkrris assigning his issue to you.
