### ISSUE TITLE
Tech Stack Update ( LOGO add ) 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [vigneshshettyin/Flask-Generate-Certificate#39]
### What part(s) of the article would you like to see updated?
Logo of tech stacks used !

I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !! 
![Screenshot 2021-03-12 224657](https://user-images.githubusercontent.com/76584243/110977004-9d6e3080-8387-11eb-83dd-1f807e9193c9.png)

Will look like this and style or more details will be discussed before making changes !!

**Comment by APratham** [comment]
@rohank2502 Kindly elaborate your concern. From what I could understand, you want to add logos of the tech stacks being used in this project, am I right?

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> @rohank2502 Kindly elaborate your concern. From what I could understand, you want to add logos of the tech stacks being used in this project, am I right?

Yes exactly square shape logo with their name size is small not much big it will look great

**Comment by shades-7** [comment]
> I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!

@rohank2502 please edit the description of  your issue and use one of the issues templates

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> > I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!
> 
> @rohank2502 please edit the description of your issue and use one of the issues templates

Ok !!
