### ISSUE TITLE
API Key Model and Tables in Dashboard

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#390]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
For the previous issue, we don't have any API Key model.

### Describe the solution you'd like
There will be an API key model. Also, in the user's dashboard and admin's dashboard, there will be an API section.
For the users, they will also have a generate api key button and for the admin, they will have an approve button to approve the api key.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Okay, @ashutoshkrris assigning this issue to you.
