### ISSUE TITLE
Add API Documentation

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#393]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
There is no API documentation

### Describe the solution you'd like
I'll add API documentation in the API page

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Hey, @ashutoshkrris assigning this issue to you.
