### ISSUE TITLE
Convert the below xd design to code

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Flask-Generate-Certificate#396]
### Is your feature request related to a problem? Please describe.
Convert this (https://drive.google.com/drive/folders/1FEQUV5YTw2fZbl0DNuZ9EZfm62d2rTrX) xd design to code strictly use layout size (3508*2480px) ie a4 horizontal. Please update progress daily with screenshots. 

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by arpit456jain** [comment]
Hey @vigneshshettyin is this related to web development?

**Comment by vigneshshettyin** [comment]
> Hey @vigneshshettyin is this related to web development?

Yes

**Comment by TrojanTarun** [comment]
Can I work on this issue.

**Comment by vigneshshettyin** [comment]
Yes, @TrojanTarun assigning this issue to you.

**Comment by arpit456jain** [comment]
Hey @vigneshshettyin how to open that file with.xd extension i am confused 😅

**Comment by vigneshshettyin** [comment]
> Hey @vigneshshettyin how to open that file with.xd extension i am confused

You should open using Adobe XD(https://www.adobe.com/in/products/xd.html) @arpit456jain
