### ISSUE TITLE
Add issue templates 

### ISSUE THREAD

**Issue by Akash20x** [vigneshshettyin/Flask-Generate-Certificate#4]
I want to add issue templates for proposal, feature and documentation types so that there is proper way to create a new issue in your repo.

Please assign me this task as a part of GSSoC'21
and add necessary labels.

**Comment by vigneshshettyin** [comment]
Sure!

**Comment by Akash20x** [comment]
Please assign me and add GSSoC'21 label

**Comment by vigneshshettyin** [comment]
![Capture](https://user-images.githubusercontent.com/77713888/110288216-ae2c4880-800d-11eb-92df-9fc8c3c13826.PNG)
It's not showing. Let me invite you as a collaborator and check.

**Comment by Akash20x** [comment]
![Screenshot_2021-03-08-14-51-02-143_com android chrome](https://user-images.githubusercontent.com/46225357/110301244-dae85c00-801d-11eb-8a33-5280d4ff33cc.jpg)


It's showing this on click the invitation

**Comment by Akash20x** [comment]
I think I will do this task without assigning,
Please add GSSoC'21, documentation and good first issue as labels

**Comment by vigneshshettyin** [comment]
> ![Screenshot_2021-03-08-14-51-02-143_com android chrome](https://user-images.githubusercontent.com/46225357/110301244-dae85c00-801d-11eb-8a33-5280d4ff33cc.jpg)
> 
> It's showing this on click the invitation

I think invitation got expired. I am sending it again.

**Comment by vigneshshettyin** [comment]
> I think I will do this task without assigning,
> Please add GSSoC'21, documentation and good first issue as labels

Okay.

**Comment by Akash20x** [comment]
> ![Screenshot_2021-03-08-14-51-02-143_com android chrome](https://user-images.githubusercontent.com/46225357/110301244-dae85c00-801d-11eb-8a33-5280d4ff33cc.jpg)
> 
> It's showing this on click the invitation

Also send it again just to check by this method it is possible to assign me or not

**Comment by subhangi2731** [comment]
can you assign this issue to me?

**Comment by vigneshshettyin** [comment]
> can you assign this issue to me?

This has already been assigned to @Akash20x . Check for any other for eg any design changes, secure login changes etc..

**Comment by vigneshshettyin** [comment]
> I think I will do this task without assigning,
> Please add GSSoC'21, documentation and good first issue as labels

@Akash20x  I am waiting for you to accept the request.
![Screenshot 2021-03-09 093927](https://user-images.githubusercontent.com/77713888/110417364-7976ca80-80bb-11eb-9b30-8a73761fefbb.png)

**Comment by Akash20x** [comment]
I accepted your request

**Comment by nikhilisaac** [comment]
can you kindly assign me to this issue as part of gssoc21

**Comment by vigneshshettyin** [comment]
> I accepted your request

Okay, I have assigned it to you.

**Comment by vigneshshettyin** [comment]
> can you kindly assign me to this issue as part of gssoc21

This has already been assigned to @Akash20x  . Check for any other for eg any design changes, secure login changes etc..

**Comment by Aayush-hub** [comment]
@vigneshshettyin Sir recent commit has disturbed the repo's workflow. If I am opening a issue, it gets auto assigned to `Akash20x`. Please look into it.

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin Sir recent commit has disturbed the repo's workflow. If I am opening a issue, it gets auto assigned to `Akash20x`. Please look into it.

Please check now.

**Comment by Aayush-hub** [comment]
> > @vigneshshettyin Sir recent commit has disturbed the repo's workflow. If I am opening a issue, it gets auto assigned to `Akash20x`. Please look into it.
> 
> Please check now.

@vigneshshettyin Same problem still continues.
