### ISSUE TITLE
Integrating Profile Page

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Flask-Generate-Certificate#407]
### Is your feature request related to a problem? Please describe.
You can find the profile page here (https://github.com/vigneshshettyin/Flask-Generate-Certificate/tree/main/templates/pop-up-profilepage) integrate it to dashboard. 

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by ashutoshkrris** [comment]
I want to work on it @vigneshshettyin

**Comment by vigneshshettyin** [comment]
> 
> 
> I want to work on it @vigneshshettyin

Okay, @ashutoshkrris assigning this issue to you.
