### ISSUE TITLE
Create config.yml file for greeting bot.

### ISSUE THREAD

**Issue by Aayush-hub** [vigneshshettyin/Flask-Generate-Certificate#42]
### Is your feature request related to a problem? Please describe.
As a first time contributor,
I need a bot to help guide my first contribution,
so that I can follow this org's contribution guidelines.

### Describe the solution you'd like
We can add a greeting bot which will greet first time contributors with a message and guide them to contribute.

**Comment by Aayush-hub** [comment]
@APratham @vigneshshettyin Can I work on it?

**Comment by shades-7** [comment]
@Aayush-hub go ahead
