### ISSUE TITLE
Creating About us page in React

### ISSUE THREAD

**Issue by subhangi2731** [vigneshshettyin/Flask-Generate-Certificate#421]
This will be the portfolio page where the information about the project will be displayed and about the team to be known to the users.

**Comment by subhangi2731** [comment]
@vigneshshettyin please assign this issue to me

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin please assign this issue to me

Yes @subhangi2731 assigning this issue to you.

**Comment by vigneshshettyin** [comment]
Closing this issue until further notice!
