### ISSUE TITLE
Create a Public api to access all certificate details

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Flask-Generate-Certificate#422]
### Is your feature request related to a problem? Please describe.
Create a Public api to access all certificate details

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by ashutoshkrris** [comment]
i would like to work on this

**Comment by vigneshshettyin** [comment]
Yes, @ashutoshkrris assigning this issue to you.
