### ISSUE TITLE
Removing Category Section 

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Flask-Generate-Certificate#434]
### **Describe the bug**
Changing implementation hence removing category section is necessary.

**Comment by ashutoshkrris** [comment]
I can work on this.

**Comment by vigneshshettyin** [comment]
Yup, @ashutoshkrris assigning this issue to you.

**Comment by Sukriti-sood** [comment]
@vigneshshettyin Can you explain this Issue
