### ISSUE TITLE
Documentation on the process of setting up eslint and making the code prettier and adding inline support JS to ESlint

### ISSUE THREAD

**Issue by subhangi2731** [vigneshshettyin/Flask-Generate-Certificate#447]
I will write the steps in the documentation of setting up eslint and linting the code and then add inline JS support to eslint

**Comment by subhangi2731** [comment]
@vigneshshettyin please assign this issue to me

**Comment by vigneshshettyin** [comment]
Okay, @subhangi2731

**Comment by vigneshshettyin** [comment]
Closing this issue until further notice!
