### ISSUE TITLE
Typo Fix & Documentation Improvement 

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Flask-Generate-Certificate#458]
### What part(s) of the article would you like to see updated?
Please link the cloud docs (https://github.com/vigneshshettyin/Flask-Generate-Certificate/tree/main/docs) to How to use section in readme (https://github.com/vigneshshettyin/Flask-Generate-Certificate#how-to-use-).  

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by simonnepinto** [comment]
Can I work on this issue?

**Comment by vigneshshettyin** [comment]
Yes, @simonnepinto assigning this issue to you.
