### ISSUE TITLE
certificate templates are not downloadable

### ISSUE THREAD

**Issue by TrojanTarun** [vigneshshettyin/Flask-Generate-Certificate#459]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Hey, @TrojanTarun assigning this issue to you.
