### ISSUE TITLE
README file : command missing 💻 

### ISSUE THREAD

**Issue by ArchishmanSengupta** [vigneshshettyin/Flask-Generate-Certificate#47]
# The README file to `How to use` goes like this:
![issue6-1](https://user-images.githubusercontent.com/71402528/111038893-46349280-8451-11eb-9d7d-57cca8453108.png)

## Whereas the proper installing and starting should include ``flask run`` as suggested by @APratham 
![issue6](https://user-images.githubusercontent.com/71402528/111038939-754b0400-8451-11eb-982f-23bcebbbfa1f.png)

Please assign me the task!
Thank you

**Comment by shades-7** [comment]
@ArchishmanSengupta Thanks for bringing this to our notice but this issue has already been raised and assigned https://github.com/vigneshshettyin/Flask-Generate-Certificate/issues/34

**Comment by ArchishmanSengupta** [comment]
no problem 👍🏼
