### ISSUE TITLE
Add Official Links for Technologies used.

### ISSUE THREAD

**Issue by NEERAJAP2001** [vigneshshettyin/Flask-Generate-Certificate#51]
### Is your feature request related to a problem? Please describe.
So, Adding official links for technologies used would help people understand more about the tech used.

### Describe the solution you'd like
Under the technologies used section, when clicked a technology we would navigate them to the official Docs of Tech.
I'm assuming adding links [Here](https://github.com/vigneshshettyin/Flask-Generate-Certificate/blob/ae190805643df569720d8076c6b0a8296f4d1d18/templates/index.html#L283) would solve the issue.

### Describe how this feature will be useful to our readers.
They will learn more about the Tech Used Eg: Say Python, they will be navigated to the official page of python, where they can learn more about that tech.

### Additional context
![Screenshot (256)](https://user-images.githubusercontent.com/65017645/111105129-48454100-8578-11eb-91af-b340fbdb71be.png)
On Clicking Tech, The user would be navigated to the official Doc

**If :
this issue sounds trivial or may deteriorate Product then feel free to close the issue.**
**Else:
I'd Like to work on this as a part of the GSSOC-21 program.**
Thanks !!
<hr/>

Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.  
If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto-assigned.  
Then you can directly start working on the issue.

**Comment by vigneshshettyin** [comment]
Go ahead!
Assigning to you

**Comment by NEERAJAP2001** [comment]
@vigneshshettyin  Can you put Level Tag as well !! 
Thanks

**Comment by NEERAJAP2001** [comment]
@vigneshshettyin So, I was working on this I need help with the official links of these tech. 
[Here](https://github.com/vigneshshettyin/Flask-Generate-Certificate/tree/main/static/images) is the directory
I need official Links for :
1.png
6.png
7.png
Thanks

**Comment by vigneshshettyin** [comment]
You can skip those @NEERAJAP2001
