### ISSUE TITLE
Create Code of Conduct

### ISSUE THREAD

**Issue by muthuannamalai12** [vigneshshettyin/Flask-Generate-Certificate#52]
I would like to add a code of conduct file as code of conduct is a necessary file which the contributors need to follow so that everyone follows a decorum.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of Girl Script Summer Of Code. Kindly assign it to me.

**Comment by shades-7** [comment]
@muthuannamalai12 please change your issue description and use one of the issue template for writing issues. Please visit contributing.md file
