### ISSUE TITLE
make the badges of single type

### ISSUE THREAD

**Issue by Umesh-01** [vigneshshettyin/Flask-Generate-Certificate#524]
### What part(s) of the article would you like to see updated?

All the badges are of different type, see this image...

![image](https://user-images.githubusercontent.com/83420185/124012108-60917c80-d9fe-11eb-8bc1-d25a38cb8ba2.png)

**I will make these badges of single type.**

![image](https://user-images.githubusercontent.com/83420185/124012422-c5e56d80-d9fe-11eb-8c6e-edc4b0221e9a.png)

### Which Program are you part of?

- [x] LGMSOC-21
- [ ] Any other

**Comment by Umesh-01** [comment]
@vigneshshettyin @ashutoshkrris Should I work on this issue??

**Comment by vigneshshettyin** [comment]
Yes, @Umesh-01 you can work on this.
