### ISSUE TITLE
Unable to deploy to Google Cloud

### ISSUE THREAD

**Issue by yaswanth37** [vigneshshettyin/Flask-Generate-Certificate#544]
The present version of the script lacks the <app.yaml> file needed to be deployed to the google cloud.

I am an noob and request for information on the same.

Thank You

**Comment by vigneshshettyin** [comment]
Apologies for the late reply!!

Hey, @yaswanth37 you can refer to google cloud docs it's straightforward (https://cloud.google.com/appengine/docs/flexible/python/quickstart). You would also need Postgres for the database (https://cloud.google.com/sql/docs/postgres).  If you face any problems in setting up feel free to start a discussion our team will help you out. 

I hope this helps you.

**Comment by yaswanth37** [comment]
@vigneshshettyin sir, I have tried to followed the Google Docs and on successful upload of files and attempt to deploy the application it poped up error saying <app.yaml> file is missing.

If anyone is willing to help me deploy the application I would be privileged under their guidance.

Thank You.

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin sir, I have tried to followed the Google Docs and on successful upload of files and attempt to deploy the application it poped up error saying <app.yaml> file is missing.
> 
> If anyone is willing to help me deploy the application I would be privileged under their guidance.
> 
> Thank You.

Hey, @ashutoshkrris can you help @yaswanth37 with deploying.

**Comment by yaswanth37** [comment]
> > @vigneshshettyin sir, I have tried to followed the Google Docs and on successful upload of files and attempt to deploy the application it poped up error saying <app.yaml> file is missing.
> > If anyone is willing to help me deploy the application I would be privileged under their guidance.
> > Thank You.
> 
> Hey, @ashutoshkrris can you help @yaswanth37 with deploying.

Thank You Sir.

@ashutoshkrris will wait for your response.
