### ISSUE TITLE
Unequal card heights

### ISSUE THREAD

**Issue by AsthaDad** [vigneshshettyin/Flask-Generate-Certificate#55]
### **Describe the bug**
In SERVICES section both cards are of different size.

### **Expected behavior**
To make card heights equal in order to ensure a consistent ui/ux

### **Screenshots**
![Capture](https://user-images.githubusercontent.com/56781858/111164521-00f88980-8553-11eb-9ea4-a7dc166c2541.PNG)

### **Additional context**

Note: If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.
If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.

**Comment by vigneshshettyin** [comment]
Okay. Please mention if you are a gssoc21 contributor

**Comment by AsthaDad** [comment]
Yes , I'm a gssoc21 contributor .

**Comment by shades-7** [comment]
Are you sure they are of unequal length n it's not a hover effect @AsthaDad

**Comment by AsthaDad** [comment]
Actually I have mistaken it . I will take care next time before creating issue .
Kindly delete this issue @shades-7  or @vigneshshettyin

**Comment by shades-7** [comment]
@AsthaDad no problem
