### ISSUE TITLE
Changing the footer section

### ISSUE THREAD

**Issue by gunjan-g** [vigneshshettyin/Flask-Generate-Certificate#561]
### Is your feature request related to a problem? Please describe.
The footer section, is a combination of form and information, which is somewhat odd according to a UI design

### Describe the solution you'd like
The form and the footer section should be made separate to each other

### Describe alternatives you've considered
We can make two different divs for connecting and the footer

### Describe how this feature will be useful to our readers.
It'll make the website more attractive according to UI design

### Which Program are you part of?

- [x] LGMSOC21

### Additional context
![image](https://user-images.githubusercontent.com/81305824/126080476-f4846200-5860-4dda-9a05-c4aa858f13d2.png)

**Comment by gunjan-g** [comment]
@vigneshshettyin please assign me this issue

**Comment by vigneshshettyin** [comment]
Okay, @gunjan-g assigning this issue to you.

**Comment by gunjan-g** [comment]
@vigneshshettyin I'm not able to see my changes, could you suggest me a way to do so

**Comment by gunjan-g** [comment]
@vigneshshettyin I'm not able to see my changes, could you suggest me a way to do so

**Comment by vigneshshettyin** [comment]
Hey, @gunjan-g have you followed all steps given in (https://github.com/vigneshshettyin/Flask-Generate-Certificate/blob/main/docs/INSTALLATION.md)

**Comment by gunjan-g** [comment]
Sir, I have no knowledge of python and flask, should i just follow the given steps as it is

**Comment by vigneshshettyin** [comment]
> Sir, I have no knowledge of python and flask, should i just follow the given steps as it is

Yes, pls follow the installation instruction given if you still face a problem start a discussion our team will help you. @gunjan-g

**Comment by gunjan-g** [comment]
Sir, I am not able to activate envScripts, it shows command not found

**Comment by vigneshshettyin** [comment]
> Sir, I am not able to activate envScripts, it shows command not found

@ashutoshkrris can you help @gunjan-g

**Comment by ashutoshkrris** [comment]
Sure @vigneshshettyin 
Hey @gunjan-g, could you please DM me over discord(ashutoshkrris#8674) so that I can see what error are you getting clearly?

**Comment by Sin-Sumit** [comment]
@vigneshshettyin it is updated or @gunjan-g still working on this. If not Please assign me.

**Comment by vigneshshettyin** [comment]
No, it's not updated yet if you are interested you can take it up. I can assign this issue to you.  @Sin-Sumit

**Comment by Sin-Sumit** [comment]
Ok, let me assign this.

**Comment by Sin-Sumit** [comment]
And please describe where you want it, like before the info section.

**Comment by Sin-Sumit** [comment]
@ashutoshkrris I need your help with installation purposes.

**Comment by ashutoshkrris** [comment]
Yep sure @Sin-Sumit!
Come over discord

**Comment by Sin-Sumit** [comment]
@vigneshshettyin Today I run the app and I find it good according to webapp. And it doesn't need any change, because if form section is put above the footer then footer have to be much content so that it looks filled.
TIll now it is good.

**Comment by Sin-Sumit** [comment]
@vigneshshettyin  you can close this issue if it looks good to you.
