### ISSUE TITLE
Dockerizing the Project!

### ISSUE THREAD

**Issue by jain-rishabh-21** [vigneshshettyin/Flask-Generate-Certificate#57]
### Is your feature request related to a problem? Please describe.
It will reduce the time required for the initial setup and also resolve the issues faced during the project installation.

### Describe the solution you'd like
Will be using docker for the project

### Describe how this feature will be useful to our readers.
Will reduce the time taken by the developers in installing and also resolve development issues on different platforms 

<hr/>

Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.  
If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.  
Then you can directly start working on the issue.

**Comment by jain-rishabh-21** [comment]
Discord username: krackerzzz#4371

**Comment by shades-7** [comment]
Go ahead @jain-rishabh-21 but keep updating in every two days

**Comment by jain-rishabh-21** [comment]
Can you please add the labels!

**Comment by APratham** [comment]
@jain-rishabh-21 I just wanted to check, is there an update?

**Comment by jain-rishabh-21** [comment]
Hey @APratham , I am getting an error while working on the project, I have asked ashutosh!

**Comment by jain-rishabh-21** [comment]
Rest everything is done from my side!

**Comment by vigneshshettyin** [comment]
> Hey @APratham , I am getting an error while working on the project, I have asked ash

> Hey @APratham , I am getting an error while working on the project, I have asked ashutosh!

Are you still facing the same error?
