### ISSUE TITLE
The subscribe button is attached to the email form

### ISSUE THREAD

**Issue by barsha119** [vigneshshettyin/Flask-Generate-Certificate#60]
### Is your feature request related to a problem? Please describe.
Yes, The subscribe button should not be attached to the email form , I think it's not looking good
![Screenshot 2021-03-18 123639](https://user-images.githubusercontent.com/56728512/111602353-4342f480-87f9-11eb-8bba-2ebcd41bd0f7.png)

### Describe the solution you'd like
The button and the form should have some space between them

### Describe alternatives you've considered
I want to provide some space at the left side of the buttons

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.  
If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.  
Then you can directly start working on the issue.

**Comment by vigneshshettyin** [comment]
Okay. You can work on it.

**Comment by vigneshshettyin** [comment]
> ### Is your feature request related to a problem? Please describe.
> Yes, The subscribe button should not be attached to the email form , I think it's not looking good
> ![Screenshot 2021-03-18 123639](https://user-images.githubusercontent.com/56728512/111602353-4342f480-87f9-11eb-8bba-2ebcd41bd0f7.png)
> 
> ### Describe the solution you'd like
> The button and the form should have some space between them
> 
> ### Describe alternatives you've considered
> I want to provide some space at the left side of the buttons
> 
> ### Describe how this feature will be useful to our readers.
> A clear and concise description of how this feature will be useful for our other readers.
> 
> ### Additional context
> Add any other context or screenshots about the feature request here.
> 
> Note:
> If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.
> If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
> Then you can directly start working on the issue.

Are you gssoc21 participant ?

**Comment by barsha119** [comment]
> > ### Is your feature request related to a problem? Please describe.
> > Yes, The subscribe button should not be attached to the email form , I think it's not looking good
> > ![Screenshot 2021-03-18 123639](https://user-images.githubusercontent.com/56728512/111602353-4342f480-87f9-11eb-8bba-2ebcd41bd0f7.png)
> > ### Describe the solution you'd like
> > The button and the form should have some space between them
> > ### Describe alternatives you've considered
> > I want to provide some space at the left side of the buttons
> > ### Describe how this feature will be useful to our readers.
> > A clear and concise description of how this feature will be useful for our other readers.
> > ### Additional context
> > Add any other context or screenshots about the feature request here.
> > Note:
> > If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.
> > If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
> > Then you can directly start working on the issue.
> 
> Are you gssoc21 participant ?

yes

**Comment by arpit456jain** [comment]
I was also going to create this issue but fortunately i saw it i had already solve this issue it will look something like this
<img width="960" alt="email form" src="https://user-images.githubusercontent.com/55352601/111860778-e87fd900-896f-11eb-87d6-91f3f81d0a9d.png">
I had added only 1 line of css and edited 2 line of css that's it.
