### ISSUE TITLE
[GSSOC'21] Order of pricing and team in the Nav Bar doesn't match with the content.

### ISSUE THREAD

**Issue by shonali2600** [vigneshshettyin/Flask-Generate-Certificate#62]
### **Describe the bug**
While clicking on pricing and team in the navbar in the same order, it leads to down the page first then move upward.

### **To Reproduce**
1. Go to 'navbar'
2. Click on 'pricing' first then 'team'
3. See an error

### **Expected behavior**
Pricing should come first on the main page, then the Team section should come. 

Note: If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.
If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.

**Comment by vigneshshettyin** [comment]
Hey, @shonali2600 I have assigned it to you. You can work on it. If you are a gssoc'21 participant kindly mention it in the issue so, that we can assign the necessary tags.

**Comment by shonali2600** [comment]
@vigneshshettyin  sir, I'm a GSSOC'21 participant, as you said that you assigned this issue to me so I started working on it, so sir kindly assign it to me.

**Comment by APratham** [comment]
@vigneshshettyin It is mentioned in the title, just not where it is supposed to be 😀

@shonali2600 If you mention GSSOC in the first issue comment, the bot auto-assigns the GSSOC21 label. That's what Vignesh was talking about I think

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin It is mentioned in the title, just not where it is supposed to be 😀
> 
> @shonali2600 If you mention GSSOC in the first issue comment, the bot auto-assigns the GSSOC21 label. That's what Vignesh was talking about I think

Ohh snap I didn't notice that 🤣 @shonali2600 @APratham
