### ISSUE TITLE
[GSSOC'21] Adding cards to the Mentors and contributors.

### ISSUE THREAD

**Issue by shonali2600** [vigneshshettyin/Flask-Generate-Certificate#63]
### Is your feature request related to a problem? Please describe.
Photos of Mentors and contributors would look good on styled cards.

### Describe the solution you'd like
I'll add photos over the styled cards.

### Describe how this feature will be useful to our readers.
It'll look good.
<hr/>

Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.  
If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.  
Then you can directly start working on the issue.

**Comment by shades-7** [comment]
@shonali2600 show your design if you have any prototype

**Comment by shonali2600** [comment]
@shades-7  something like this...
![prototype_cards1](https://user-images.githubusercontent.com/57946528/111659273-190e2880-8833-11eb-96c5-0cdbea45b4f8.png)

**Comment by vigneshshettyin** [comment]
Hey, @shonali2600 That's great but when we have many contributors it would elongate the page which is not good. Just check this out (https://codepen.io/fixcl/pen/KwpKvb) somewhat like an infinity scroll or carousal. Check for some better design options. 

Good Luck!

**Comment by vigneshshettyin** [comment]
@shonali2600 Kindly give your response on this.

**Comment by shonali2600** [comment]
Sir I'll try to design infinity scrolling cards.

**Comment by vigneshshettyin** [comment]
> Sir I'll try to design infinity scrolling cards.

Cool

**Comment by vigneshshettyin** [comment]
Hey, @shonali2600 it's been a while we haven't heard anything from you. Kindly post your update.

**Comment by shonali2600** [comment]
@vigneshshettyin  sir, I'm working on it, It's a new thing for me, please give me some time

**Comment by vigneshshettyin** [comment]
Okay. I'll assign this issue to you then @shonali2600

**Comment by APratham** [comment]
@shonali2600 The only problem is that under GSSOC if you wish to be credited you have to do it within a timeframe. We are already well beyond that 😁. If you want to contribute just as a part of open source and not GSSOC then you can take as much time as you desire we won't have an issue with that

**Comment by shonali2600** [comment]
Ohh okay no problem @APratham sir, still I would like to contribute to this issue. I can understand it'll not be added to my score.

**Comment by shonali2600** [comment]
I made changes to mentors and it's working but on making the same changes to the contributors it doesn't work.

**Comment by vigneshshettyin** [comment]
Great, @shonali2600 make a short screen-recording and show the changes you have made.

**Comment by shonali2600** [comment]
I tried carousel on mentors, but I think it's not needed there as there is enough space available for that. 
Not working for contributors.

https://user-images.githubusercontent.com/57946528/112876000-957df280-90e2-11eb-9158-34b143140a7e.mp4

**Comment by shades-7** [comment]
@shonali2600 good work have you send any PR?

**Comment by shonali2600** [comment]
No, I haven't as it's not working for contributors.

**Comment by shades-7** [comment]
what are the issues you are facing?

**Comment by shonali2600** [comment]
I've added the same code to the contributors, but it's not scrolling just like mentors. I've also included this thing in the video.

**Comment by shades-7** [comment]
Please share the screenshots of the codes

**Comment by shonali2600** [comment]
![carousel1](https://user-images.githubusercontent.com/57946528/113094806-fce59080-920f-11eb-9f84-40ba91cb719b.png)
![carousel2](https://user-images.githubusercontent.com/57946528/113094808-feaf5400-920f-11eb-9c37-179e26f9cca3.png)

**Comment by shades-7** [comment]
@shonali2600 I am looking into it can you also send the error message happening on your terminal

**Comment by shonali2600** [comment]
@shades-7 ma'am there is no error, the problem is, this JS code is not working for the contributors.

**Comment by vigneshshettyin** [comment]
> @shades-7 ma'am there is no error, the problem is, this JS code is not working for the contributors.

Hey, @shonali2600 have you committed these changes to your forked repo. If yes please share the link here.

**Comment by shades-7** [comment]
> > @shades-7 ma'am there is no error, the problem is, this JS code is not working for the contributors.
> 
> Hey, @shonali2600 have you committed these changes to your forked repo. If yes please share the link here.

agree with @vigneshshettyin please push the changes on your repo and share the link

**Comment by shonali2600** [comment]
Here is the link to my repo https://github.com/shonali2600/Flask-Generate-Certificate, I've added the changes to it.

**Comment by shades-7** [comment]
> Here is the link to my repo https://github.com/shonali2600/Flask-Generate-Certificate, I've added the changes to it.

Thanks will look into it, and be back soon

**Comment by KaizenGirl1111** [comment]
Hello, I have the idea of making flip cards. It is the brilliance of CSS. You please assign this task to me.

**Comment by vigneshshettyin** [comment]
Yup, @KaizenGirl1111 assigning to you. Are you a gssoc'21 participant?

**Comment by arpit456jain** [comment]
@vigneshshettyin can two people work on same issue ?

**Comment by vigneshshettyin** [comment]
Yes only if the participant is not updating in 2 days. If @KaizenGirl1111 doesn't make a pr within 2 days then this issue can be assigned to you. @arpit456jain

**Comment by vigneshshettyin** [comment]
Hey, @KaizenGirl1111 waiting for your update

**Comment by KaizenGirl1111** [comment]
@vigneshshettyin yes sir
https://www.github.com/KaizenGirl1111/Avni_Protege_Project.github.io/tree/main/index.html 
I've the flip card CSS/html code here

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin yes sir
> https://www.github.com/KaizenGirl1111/Avni_Protege_Project.github.io/tree/main/index.html 
> I've the flip card CSS/html code here

Hey, @KaizenGirl1111 that's great it would be great if you could post a screen recording of the flip card here.

**Comment by KaizenGirl1111** [comment]
https://vimeo.com/537989025 
Video link of the code

**Comment by KaizenGirl1111** [comment]
![Screenshot_20210417-094006_GitHub](https://user-images.githubusercontent.com/73153808/115102012-14d64780-9f66-11eb-91c3-59f551851e24.jpg)
![Screenshot_20210417-094021_GitHub](https://user-images.githubusercontent.com/73153808/115102016-16a00b00-9f66-11eb-995b-b295577e8291.jpg)
![Screenshot_20210417-094045_GitHub](https://user-images.githubusercontent.com/73153808/115102019-1738a180-9f66-11eb-9a12-e5d3cf7cd759.jpg)

**Comment by KaizenGirl1111** [comment]
> https://vimeo.com/537989025
> Video link of the code

This is the video of working of code

**Comment by vigneshshettyin** [comment]
> > https://vimeo.com/537989025
> > Video link of the code
> 
> This is the video of working of code

It's too basic @KaizenGirl1111

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin can two people work on same issue ?

Hey, @arpit456jain assigning this issue to you

**Comment by arpit456jain** [comment]
> > @vigneshshettyin can two people work on same issue ?
> 
> Hey, @arpit456jain assigning this issue to you

Ok i will try it .
It will be a great task to me and the tuffest one till now but i will give my best 👍

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/115113071-090a7580-9fa6-11eb-896d-4f1a892c1231.mp4

@vigneshshettyin Please check this if this is ok or not.

I had tried a lot to increase its speed but its not working I hope its is not very slow

**Comment by vigneshshettyin** [comment]
> 
> https://user-images.githubusercontent.com/55352601/115113071-090a7580-9fa6-11eb-896d-4f1a892c1231.mp4
> 
> @vigneshshettyin Please check this if this is ok or not.
> 
> I had tried a lot to increase its speed but its not working I hope its is not very slow 

It's fine you can make pr @arpit456jain

**Comment by arpit456jain** [comment]
ok @vigneshshettyin

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain carousel is not working.

**Comment by arpit456jain** [comment]
@vigneshshettyin how it is possible 😅 it is working in my system i had made a video for that😅

**Comment by arpit456jain** [comment]
Let me check 1 min

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin how it is possible 😅 it is working in my system i had made a video for that😅

Yeah, I don't know why changes didn't reflect in the live version. @arpit456jain

**Comment by arpit456jain** [comment]
@vigneshshettyin in my system its working fine .
Please try to refresh may be some css file is not loaded properly

**Comment by arpit456jain** [comment]
> > @vigneshshettyin how it is possible 😅 it is working in my system i had made a video for that😅
> 
> Yeah, I don't know why changes didn't reflect in the live version. @arpit456jain

😅😅😅

**Comment by arpit456jain** [comment]
> > @vigneshshettyin how it is possible 😅 it is working in my system i had made a video for that😅
> 
> Yeah, I don't know why changes didn't reflect in the live version. @arpit456jain

it is  working on your local sys or not ??

**Comment by arpit456jain** [comment]
@vigneshshettyin i had again pull the latest code in a new folder and its working fine . 😅😅😅

**Comment by vigneshshettyin** [comment]
Yeah in live version it's not (https://cgv.in.net/) anyway let's debug it @arpit456jain

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/115117665-65c55a80-9fbd-11eb-8ea4-4e3883bdfb13.mp4

**Comment by arpit456jain** [comment]
@vigneshshettyin it is working live in my phone 😅😅😅

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/115118259-f2711800-9fbf-11eb-8cf1-ac590210b7be.mp4

@vigneshshettyin it is working live for me in laptop also 😅😅😅😅😅😅

**Comment by vigneshshettyin** [comment]
That's really weird I have tested it on 3 different browsers, clearing cache, trying hard refresh but it's the same. @arpit456jain https://www.loom.com/share/e557bf250b3c4cdfbbde4ed540054806

**Comment by arpit456jain** [comment]
@vigneshshettyin well Its really very wierd .
well i had checked this in my mobile so i think there is no problem on live 

did you check it on your phone ??

**Comment by vigneshshettyin** [comment]
Yup, there also it's same. I have told mentors to check just waiting for their confirmation. @arpit456jain

**Comment by arpit456jain** [comment]
@vigneshshettyin is it working fine or not?

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin is it working fine or not?

Yup, it's fine now. @arpit456jain 
Thanks for the support!

**Comment by arpit456jain** [comment]
> > @vigneshshettyin is it working fine or not?
> 
> Yup, it's fine now. @arpit456jain
> Thanks for the support!

My pleasure @vigneshshettyin 🙂
