### ISSUE TITLE
Remove /assign part from issue template

### ISSUE THREAD

**Issue by Aayush-hub** [vigneshshettyin/Flask-Generate-Certificate#64]
### **Describe the bug**
Remove `/assign` note from issue templates as workflow of `/assign` is not there as suggested by @APratham .

**Comment by Aayush-hub** [comment]
@shades-7 @vigneshshettyin  Can I look into this improvement?

**Comment by APratham** [comment]
I am not sure where I suggested that `/assign` is a part of workflow. It could have been removed as according to rules you can't self assign. You have to wait for a moderator or project admin to assign it to you

**Comment by Aayush-hub** [comment]
@APratham Yes , the workflow is removed but Note for contributors in issue template to self assign is still there, so this issue is for that.

**Comment by vigneshshettyin** [comment]
Hey, @Aayush-hub it's already fixed.
