### ISSUE TITLE
Add checkbox to issue templates

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Flask-Generate-Certificate#66]
### What part(s) of the article would you like to see updated?

Add a checkbox in issue templates to select gssoc or other to distinguish contributors. This would also help mentors too to assign necessary labels.

**Comment by Aayush-hub** [comment]
@vigneshshettyin Can I look into it?

**Comment by vigneshshettyin** [comment]
Yup @Aayush-hub you can work on it.
