### ISSUE TITLE
Form Validation (Gsoc21 participant)

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#68]
### **Describe the bug**
There is bug in the contact us form like when i tried to give any alphabet in phone number field it cause a server error. when i run the same thing on local server it shows KeyError: 'HTTP_X_FORWARDED_FOR' and secondly i am able to send this form with only 1 letter of name,1 digit of number .

### **Expected behavior**
It should display a message to user that form is not filled correctly please fill it correctly that's it.
<img width="960" alt="1" src="https://user-images.githubusercontent.com/55352601/111772921-78bc1080-88d3-11eb-9af0-bafcf1ac196c.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/55352601/111772936-7eb1f180-88d3-11eb-87cc-10a2a73a06b9.png">
<img width="960" alt="3" src="https://user-images.githubusercontent.com/55352601/111773030-a012dd80-88d3-11eb-92a8-dc127908d149.png">

**Comment by APratham** [comment]
@arpit456jain Please add GSSOC in your issue comment while creating an issue. That enables the bot to auto-assign the mandatory label atleast

**Comment by arpit456jain** [comment]
Can i try to solve it??

**Comment by APratham** [comment]
Sorry my bad, I didn't assign you 😅

**Comment by APratham** [comment]
Go ahead bro, it's yours
