### ISSUE TITLE
Use thread to send emails

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#695]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
Currently we are sending emails without using thread which may pose problem.

### Describe the solution you'd like
We can use Python threads to send emails

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Committed (https://github.com/vigneshshettyin/Flask-Generate-Certificate/commit/3cdd0d4ec5adfcd7f02e042f839676a9bf15873d , https://github.com/vigneshshettyin/Flask-Generate-Certificate/commit/bac6cfada2638cb052edcd967b4d8e1ba2430b33)
