### ISSUE TITLE
Dark Theme UI

### ISSUE THREAD

**Issue by mohammedjameel24** [vigneshshettyin/Flask-Generate-Certificate#71]
### Is your feature request related to a problem? Please describe.
Switchable dark theme UI

### Describe the solution you'd like
add toggle to switch between dark and light theme

### Describe how this feature will be useful to our readers
less eye strain

### Additional context
pure javascript implementation

**Comment by mohammedjameel24** [comment]
Assign me this issue

**Comment by vigneshshettyin** [comment]
Yes assigning to you.

**Comment by vigneshshettyin** [comment]
Any updates @mohammedjameel24

**Comment by arpit456jain** [comment]
@vigneshshettyin sir Please assign me this issue, I am a Gssoc'21 participant  I will work on it as soon as possible.

**Comment by vigneshshettyin** [comment]
Yup @arpit456jain. Assigning it to you.

**Comment by vigneshshettyin** [comment]
@mohammedjameel24 As we didn't receive any response from you. We have unassigned you from this issue.

**Comment by arpit456jain** [comment]
thank you @vigneshshettyin sir.
please add the label of GSSOC'21 as I am gssoc participant

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain I have already assigned it to you.

**Comment by arpit456jain** [comment]
@vigneshshettyin  sorry sir I did't notice that label of Gssoc'21 is already added. My fault

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin sorry sir I did't notice that label of Gssoc'21 is already added. My fault

No issues @arpit456jain , any issues in setting up or working with the app feel free to start a discussion. Our team will help you out.

**Comment by arpit456jain** [comment]
ok sir.

**Comment by arpit456jain** [comment]
sir I had solved this issue I am going to create a PR Kindly Review it.

**Comment by vigneshshettyin** [comment]
> sir I had solved this issue I am going to create a PR Kindly Review it.

Check this (https://github.com/vigneshshettyin/Flask-Generate-Certificate/pull/104#issuecomment-807893180)
