### ISSUE TITLE
Redirect link is wrong (Gsoc'21)

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#74]
### **Describe the bug**
On Clicking the icon on top-left it should redirect to home page but it is redirecting to index.html which is not working correctly.
<img width="960" alt="p1" src="https://user-images.githubusercontent.com/55352601/111862426-4d8cfc00-897b-11eb-9f7f-ffa443b7c44e.png">

when I clicked on icon this page is showing
<img width="960" alt="p2" src="https://user-images.githubusercontent.com/55352601/111862441-61d0f900-897b-11eb-81a6-684065cf0e54.png">

This is very basic issue and can be solved by just editing a small line . **If this is really a issue, I can solve it** 
### **Expected behavior**
It should redirect to home page, which is in this case it should redirect to same page.

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain this is a simple change this issue should be closed in an hour.
