### ISSUE TITLE
Social Login with Google

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#76]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
Normally, users prefer logging in with Google or Facebook to avoid filling up forms.

### Describe the solution you'd like
I would like to integrate Google OAuth2 to login with Google. This way, we can fetch data like name, email and profile picture from the user's google account as well.
 
### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.
This feature will be useful for users as these days users prefer logging in with social sites over filling up a long form.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Hey, @ashutoshkrris assigning to you.

**Comment by ashutoshkrris** [comment]
Thanks @vigneshshettyin 
I'll keep updating here.

**Comment by vigneshshettyin** [comment]
> Thanks @vigneshshettyin
> I'll keep updating here.

Cool @ashutoshkrris
