### ISSUE TITLE
Add reload site functionality

### ISSUE THREAD

**Issue by Aayush-hub** [vigneshshettyin/Flask-Generate-Certificate#78]
### **Describe the bug**
Add reload site functionality when clicked on project logo in navbar, which is currently showing a error page.

### **To Reproduce**
1. Go to website deployed on herokui
2. Click on project logo in top left
3. See error

### Which Program are you part of?

- [x] GSSOC21

**Comment by vigneshshettyin** [comment]
Hey @Aayush-hub thanks for noticing it, but it has been already fixed.
