### ISSUE TITLE
Add hover effect to buttons

### ISSUE THREAD

**Issue by Aayush-hub** [vigneshshettyin/Flask-Generate-Certificate#79]
### Is your feature request related to a problem? Please describe.
Add hover effects to send message and submit feedback button.

### Describe the solution you'd like
As we can see that every button in site has hover effect, but two buttons are lacking of it. So i would like to add it.

### Which Program are you part of?

- [x] GSSOC21

**Comment by vigneshshettyin** [comment]
Okay. Assigning to you. @Aayush-hub
