### ISSUE TITLE
There is a gramatical error in the documentation.

### ISSUE THREAD

**Issue by Priyanshu078** [vigneshshettyin/Flask-Generate-Certificate#84]
### What part(s) of the article would you like to see updated?
![gramatical error](https://user-images.githubusercontent.com/66347715/112099477-976b2180-8bc9-11eb-906f-70b49517d6b4.png)

### Which Program are you part of?
GSSOC21

**Comment by Priyanshu078** [comment]
Please assign me this issue

**Comment by shades-7** [comment]
Go ahead @Priyanshu078

**Comment by vigneshshettyin** [comment]
Hey, @Priyanshu078 kindly make valid changes. Either work on creating documentation for Digital Ocean, Azure or any other cloud service on flask app deployment.

**Comment by vigneshshettyin** [comment]
Closing this issue until further notice. @Priyanshu078
