### ISSUE TITLE
Social login With Facebook

### ISSUE THREAD

**Issue by Sukriti-sood** [vigneshshettyin/Flask-Generate-Certificate#86]
### Is your feature request related to a probllem?
As Facebook is mentioned in UI , so authentication also be implemented using Facebook

### Which Program are you part of?
- [x] GSSOC21

**Comment by vigneshshettyin** [comment]
Yup @Sukriti-sood you can work on it. 
All the best!

**Comment by shades-7** [comment]
@Sukriti-sood any progress?

**Comment by Sukriti-sood** [comment]
@shades-7 doing ,

**Comment by vigneshshettyin** [comment]
> @shades-7 doing ,

Cool @Sukriti-sood
