### ISSUE TITLE
UI Changes

### ISSUE THREAD

**Issue by Sukriti-sood** [vigneshshettyin/Flask-Generate-Certificate#87]
### **Describe the bug**
UI of Login Page is good , but its not matching the Website theme.

### **To Reproduce**
Changes in UI

### Which Program are you part of?
- [x] GSSOC21

**Comment by vigneshshettyin** [comment]
Kindly mention the UI changes on which you want to work on (in brief). @Sukriti-sood

**Comment by Sukriti-sood** [comment]
> Kindly mention the UI changes on which you want to work on (in brief). @Sukriti-sood

Website Ui
![CGV-Online-Certificate-Verification-System (1)](https://user-images.githubusercontent.com/55010599/112240468-655fcb00-8c6e-11eb-9ded-7815327477be.png)

Login Page UI
![Login-CGV-Largest-Online-Verification-Network](https://user-images.githubusercontent.com/55010599/112240749-e5863080-8c6e-11eb-82b7-3e4c3e104d3d.png)

 
There is difference between ,both pages , All website has Same UI except Login Page and Also some position changes,I want to changes Color theme of this Login Page and also Some changes in POsitioning .

**Comment by vigneshshettyin** [comment]
Go ahead!
assigning to you. @Sukriti-sood

**Comment by Sukriti-sood** [comment]
@vigneshshettyin  hello Sir , I am facing an iproblem while updating CSS of related html pages changes are not render on website.

**Comment by vigneshshettyin** [comment]
Hey, @Sukriti-sood  stop the app and try rerunning it.

**Comment by Sukriti-sood** [comment]
@vigneshshettyin  I have tried this

**Comment by vigneshshettyin** [comment]
That's strange. @Sukriti-sood

**Comment by vigneshshettyin** [comment]
Will get back to you soon. @Sukriti-sood 
It would be great if you could attach the screenshots of the changes you have made. it would be easy for us to analyze the problem. Kindly start a discussion regarding the same our team will assist you.

**Comment by Sukriti-sood** [comment]
@vigneshshettyin  Ya ,I am attaching and I have queston regarding the images of login ,register and forget-password pages , They are stored in firebase?

Like I added a minor change in sb-admin-2.css

`small {
  font-size: 80%;
  color: #fdb500;
}`

(small class of text Forget password .....Create account)

But There is no changes in UI and I also tried to change images used and position of container but no changes ,

![Login-CGV-Largest-Online-Verification-Network (1)](https://user-images.githubusercontent.com/55010599/112514241-1f644d80-8dbb-11eb-8fa6-21864a43255f.png)

**Comment by shades-7** [comment]
@Sukriti-sood, please upload the screenshot of the file, where you have made the changes

**Comment by Sukriti-sood** [comment]
Like I made a color change a tag but it is not shown in website @shades-7 @vigneshshettyin 

![Screenshot from 2021-03-28 08-21-32](https://user-images.githubusercontent.com/55010599/112740948-b0474e80-8f9e-11eb-891f-f941f294004a.png)

**Comment by vigneshshettyin** [comment]
> ge a tag

Hey, @Sukriti-sood flask app sometimes takes some more time to apply the styling because of the cache stored.  Do you want to suggest some more UI changes or shall I close this issue?

**Comment by Sukriti-sood** [comment]
> > ge a tag
> 
> Hey, @Sukriti-sood flask app sometimes takes some more time to apply the styling because of the cache stored. Do you want to suggest some more UI changes or shall I close this issue?

It can be but, any changes made in  HTML are rendering but changes made in css are not rendering
I want to change the images used in login , signup and forget-password HTML but I think those images are stored in firebase.

**Comment by vigneshshettyin** [comment]
> > > ge a tag
> > 
> > 
> > Hey, @Sukriti-sood flask app sometimes takes some more time to apply the styling because of the cache stored. Do you want to suggest some more UI changes or shall I close this issue?
> 
> It can be but, any changes made in HTML are rendering but changes made in css are not rendering
> I want to change the images used in login , signup and forget-password HTML but I think those images are stored in firebase.

Yup those images are stored in the firebase. You can add new illustrations to 'static/images' locations and link them using url_for method. @Sukriti-sood

**Comment by Sukriti-sood** [comment]
> > > > ge a tag
> > > 
> > > 
> > > Hey, @Sukriti-sood flask app sometimes takes some more time to apply the styling because of the cache stored. Do you want to suggest some more UI changes or shall I close this issue?
> > 
> > 
> > It can be but, any changes made in HTML are rendering but changes made in css are not rendering
> > I want to change the images used in login , signup and forget-password HTML but I think those images are stored in firebase.
> 
> Yup those images are stored in the firebase. You can add new illustrations to 'static/images' locations and link them using url_for method. @Sukriti-sood

I tried that but css is not rendering, I don't know Is this thing  only happening on my environment

**Comment by vigneshshettyin** [comment]
Hey, @Sukriti-sood Do one thing create a new discussion our team will help you out. 
cc @shades-7

**Comment by Sukriti-sood** [comment]
@vigneshshettyin  There are more issues in UI Like Dark Mode is not available for All routes  and On Enabling Dark mode
Images used in Website has white Background  so they need to be replaced with images having Transparent Background, 
I will do them .After Completing issue #86 .,

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin  There are more issues in UI Like Dark Mode is not available for All routes  and On Enabling Dark mode
> Images used in Website has white Background  so they need to be replaced with images having Transparent Background, 
> I will do them .After Completing issue #86 .,

Yeah sure @Sukriti-sood. Create a new issue regarding it. I'll assign it to you.

**Comment by shades-7** [comment]
@Sukriti-sood did css start rendring? 
before changing the pic please share it here once for the apporval.

**Comment by Sukriti-sood** [comment]
> @Sukriti-sood did css start rendring?
> before changing the pic please share it here once for the apporval.

No mam , I will do that with HTML ,
Mam I am not changing images but  will only make their background transparent

**Comment by shades-7** [comment]
@Sukriti-sood no need to tell me mam hehehe
is there any error message on your terminal rendering CSS, like why it's not rendering?

**Comment by Sukriti-sood** [comment]
> @Sukriti-sood no need to tell me mam hehehe
> is there any error message on your terminal rendering CSS, like why it's not rendering?

Sorry Mam,
No,  there is no error message , like I have changed background image in CSS but on rendering website there is still old image and also On Inspecting there is no code change Shown, I also want to  know why it is not rendering .

**Comment by shades-7** [comment]
@Sukriti-sood why are you saying sorry 
I just asked you not to call me maam so that it doesn't sound formal. 
Try to make changes in other css file and also in different tags of the same css file and see if it's rendering

**Comment by arpit456jain** [comment]
> > @Sukriti-sood no need to tell me mam hehehe
> > is there any error message on your terminal rendering CSS, like why it's not rendering?
> 
> Sorry Mam,
> No, there is no error message , like I have changed background image in CSS but on rendering website there is still old image and also On Inspecting there is no code change Shown, I also want to know why it is not rendering .

@Sukriti-sood  try to load website with ctrl+shift+R (hard reload) this will reload the cache files also.

**Comment by Sukriti-sood** [comment]
> > > @Sukriti-sood no need to tell me mam hehehe
> > > is there any error message on your terminal rendering CSS, like why it's not rendering?
> > 
> > 
> > Sorry Mam,
> > No, there is no error message , like I have changed background image in CSS but on rendering website there is still old image and also On Inspecting there is no code change Shown, I also want to know why it is not rendering .
> 
> @Sukriti-sood try to load website with ctrl+shift+R (hard reload) this will reload the cache files also.

Thanks @arpit456jain It works

**Comment by arpit456jain** [comment]
@Sukriti-sood  your welcome happy to help.😊

**Comment by shades-7** [comment]
@Sukriti-sood any progress?

**Comment by Sukriti-sood** [comment]
@shades-7  I think this issue is Solved now, I forget to close, I am closing this.
