### ISSUE TITLE
Database Management

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#88]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
Currently, I can see that we are using `db.create_all()` command to create database. But whenever we make any changes to it, we need to delete the existing database and re-run the command, which I don't think, is good for a large scale project, specially when it has been deployed to production. 

### Describe the solution you'd like
I want to use Flask-Migrate to manage the database easily. It provides few useful commands which help us initialize the database, migrate the database whenever we make changes to the fields and upgrade or downgrade the database as per the latest migrations.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

**Comment by vigneshshettyin** [comment]
Yup, @ashutoshkrris assigning to you.
