### ISSUE TITLE
Help Desk Page is empty 

### ISSUE THREAD

**Issue by iprasandeep** [vigneshshettyin/Flask-Generate-Certificate#94]
Hey, I'm a GSSoC'21 participant, In our project help desk page is empty. So can we add chatbot or types of contact details? Please let me know if it is feasible then I would like to contribute.
![image](https://user-images.githubusercontent.com/52857138/112502144-d4910880-8daf-11eb-9325-625fe538c511.png)

**Comment by vigneshshettyin** [comment]
Hey, @prsndp we got to design and develop a helpdesk portal for raising tickets. Kindly give ideas regarding the same. I'll be assigning this issue to you.

**Comment by iprasandeep** [comment]
Yeah, @vigneshshettyin  thanks but we need some contact or help desk details for this page.

**Comment by vigneshshettyin** [comment]
> Yeah, @vigneshshettyin  thanks but we need some contact or help desk details for this page.

Yup @prsndp . If you have any other questions regarding it start a new discussion our team will help you out.

**Comment by APratham** [comment]
@prsndp You can discuss here on the pinned GSSOC discussion or else feel free to open another one as per your liking (https://github.com/vigneshshettyin/Flask-Generate-Certificate/discussions)

**Comment by iprasandeep** [comment]
> @prsndp You can discuss here on the pinned GSSOC discussion or else feel free to open another one as per your liking (https://github.com/vigneshshettyin/Flask-Generate-Certificate/discussions)

Thanks  :) @APratham
