### ISSUE TITLE
Problem in Navbar.

### ISSUE THREAD

**Issue by ayushjha952** [vigneshshettyin/Flask-Generate-Certificate#95]
### **Describe the bug**
In the Navbar after services it should show about pricing but it showing about the Team.

### Which Program are you part of?
- [x] GSSOC21

### **Additional context**
We can change the sequence of tabs in navbar.

**Comment by ayushjha952** [comment]
Can you please assign this to me?

**Comment by vigneshshettyin** [comment]
Yup, Assigning it to you. @ayushjha952

**Comment by ayushjha952** [comment]
@vigneshshettyin can you tell me one for setting up the database do I need to run all commands?

**Comment by vigneshshettyin** [comment]
Setting up the database you need to run 
```
from app import db 
db.create_all()
```
in the python shell.  @ayushjha952

**Comment by ayushjha952** [comment]
No actually I asking about the 5 step in how to use.
Do we need to execute all the four commands?

**Comment by vigneshshettyin** [comment]
Yup, if you are setting up the app for the first time you need to run all 5 commands. @ayushjha952

**Comment by ayushjha952** [comment]
I have made a PR  https://github.com/vigneshshettyin/Flask-Generate-Certificate/pull/96 can you check once.

**Comment by ayushjha952** [comment]
@vigneshshettyin you have not added the label level?
