### ISSUE TITLE
Create templates for certificates

### ISSUE THREAD

**Issue by APratham** [vigneshshettyin/Flask-Generate-Certificate#97]
### Is your feature request related to a problem? Please describe.
Create additional templates for the certificate as many as possible. This issue will be kept open for other contributions as well. 

### Describe the solution you'd like
Here is the existing certificate (https://github.com/vigneshshettyin/Flask-Generate-Certificate/blob/main/templates/certificate.html)

![certificate](https://user-images.githubusercontent.com/33273990/112513527-6bfb5900-8dba-11eb-8dd3-ea0a1d9a2407.png)

### Describe how this feature will be useful to our readers.
It will add to the UI look and feel and help others in customisation. Feel free to share your ideas. Remember to add a screenshot first of how it is supposed to look like. Even a rough drawing should be okay

While commenting, remember to share that you are a part of GSSOC or not

**Comment by AshuKV** [comment]
Can I work on this issue under GSSOC21? Kindly assign it to me.

**Comment by vigneshshettyin** [comment]
> Can I work on this issue under GSSOC21? Kindly assign it to me.

Yes @AshuKV assigning to you.

**Comment by AshuKV** [comment]
@vigneshshettyin Is it possible to add other contributors also to work on this issue?

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin Is it possible to add other contributors also to work on this issue?

Yes, i will add @AshuKV

**Comment by TrojanTarun** [comment]
I would like to work on this issue under GSSoC.

**Comment by TrojanTarun** [comment]
I have Created a certificate template mockup.


![491123-PHFEEW-124](https://user-images.githubusercontent.com/50846427/114215177-e911fb00-9982-11eb-95e2-41d8a540389f.png)

**Comment by vigneshshettyin** [comment]
Hi, Team @APratham, @shades-7  & @rexdivakar kindly review the mockup if there can be any improvements let @TrojanTarun know so, that he can start working on code quickly.

**Comment by rexdivakar** [comment]
I feel the certificate is kind of clumsy could it be more sleek and elegant!!

**Comment by TrojanTarun** [comment]
> I feel the certificate is kind of clumsy could it be more sleek and elegant!!

Hello, Mentor @rexdivakar.
please give me more suggestions so that i can improve it much better.

**Comment by rexdivakar** [comment]
> > I feel the certificate is kind of clumsy could it be more sleek and elegant!!
> 
> 
> 
> Hello, Mentor @rexdivakar.
> 
> please give me more suggestions so that i can improve it much better. 

Hey @TrojanTarun try to keep the shapes and colours simple and neat the content matters than the designs !!

**Comment by TrojanTarun** [comment]
> > > I feel the certificate is kind of clumsy could it be more sleek and elegant!!
> > 
> > 
> > Hello, Mentor @rexdivakar.
> > please give me more suggestions so that i can improve it much better.
> 
> Hey @TrojanTarun try to keep the shapes and colours simple and neat the content matters than the designs !!

Okay , I will try to improve it ASAP.

**Comment by TrojanTarun** [comment]
Hey, Mentor @rexdivakar kindly review this another mockup i have created.

![4979798](https://user-images.githubusercontent.com/50846427/114276592-df50cc00-9a44-11eb-86b4-3507819db0b0.png)

**Comment by rexdivakar** [comment]
Hey @TrojanTarun this looks sweet good job 👍

**Comment by TrojanTarun** [comment]
> Hey @TrojanTarun this looks sweet good job 👍

Thank you.

**Comment by vigneshshettyin** [comment]
@TrojanTarun you can start converting mockup to code now. All the best!!

**Comment by TrojanTarun** [comment]
> @TrojanTarun you can start converting mockup to code now. All the best!!

Okay, I will start converting the mockup into html CSS.
